-- Clean rebuild source for LITERATURE_INTRADAY_ADVISER_SEARCH_SERVICE (1207 rows).
-- Snapshot from canonical view avoids Cortex change-tracking limitation on NOT EXISTS subqueries.
-- Does NOT modify REVALIDATION or corpus text.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA KNOWLEDGE;

CREATE OR REPLACE TABLE MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_CORTEX_INDEX_SOURCE
    COMMENT = 'Cortex index snapshot of V_LITERATURE_INTRADAY_ADVISER_RAG_CORPUS (v1.1 static 1207).'
AS
SELECT
    RAG_DOCUMENT_ID,
    CARD_ID,
    EXECUTION_DIRECTION,
    EXECUTION_RELEVANCE,
    ADVISER_CLASS,
    CONCEPT_NAME,
    CONCEPT_FAMILY,
    DAILY_BAR_COMPATIBILITY,
    SOURCE_BOOK,
    SEARCH_TEXT,
    DISPLAY_TEXT
FROM MIP.KNOWLEDGE.V_LITERATURE_INTRADAY_ADVISER_RAG_CORPUS;

DROP CORTEX SEARCH SERVICE IF EXISTS MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_SEARCH_SERVICE;

CREATE CORTEX SEARCH SERVICE MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_SEARCH_SERVICE
    ON SEARCH_TEXT
    ATTRIBUTES
        EXECUTION_DIRECTION,
        EXECUTION_RELEVANCE,
        ADVISER_CLASS,
        CONCEPT_FAMILY,
        SOURCE_BOOK,
        CARD_ID
    WAREHOUSE = MIP_WH_XS
    TARGET_LAG = '365 days'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
    COMMENT = 'LONG_ONLY Brooks Intraday Adviser v1.1 static (1207). Indexing suspended after rebuild.'
    AS (
        SELECT
            RAG_DOCUMENT_ID,
            CARD_ID,
            EXECUTION_DIRECTION,
            EXECUTION_RELEVANCE,
            ADVISER_CLASS,
            CONCEPT_NAME,
            CONCEPT_FAMILY,
            DAILY_BAR_COMPATIBILITY,
            SOURCE_BOOK,
            SEARCH_TEXT,
            DISPLAY_TEXT
        FROM MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_CORTEX_INDEX_SOURCE
    );

SELECT COUNT(*) AS INDEX_SOURCE_ROWS FROM MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_CORTEX_INDEX_SOURCE;
