-- Remove duplicate BROOKS_INTRADAY_ADVISER_V1_0 attempts (keep best per symbol/day).
-- Keeps: COMPLETED with calls, highest trade_count, then call count, then newest.
-- Also drops stale RUNNING rows when a reviewable COMPLETED sibling exists.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE OR REPLACE TEMPORARY TABLE _ADVISER_V1_DEDUPE_LOSERS AS
WITH base AS (
    SELECT
        a.ADVISER_ATTEMPT_ID,
        a.SYMBOL,
        a.TRADING_DATE,
        a.STATUS,
        a.CREATED_AT,
        COALESCE(s.TRADE_COUNT, 0) AS TRADE_COUNT,
        (
            SELECT COUNT(*)
            FROM MIP.APP.BROOKS_INTRADAY_ADVISER_CALL c
            WHERE c.ADVISER_ATTEMPT_ID = a.ADVISER_ATTEMPT_ID
        ) AS CALL_COUNT
    FROM MIP.APP.BROOKS_INTRADAY_ADVISER_ATTEMPT a
    LEFT JOIN MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT s
        ON s.CONTEXT_ATTEMPT_ID = a.ADVISER_ATTEMPT_ID
    WHERE a.CONFIG_JSON:adviser_version::STRING = 'BROOKS_INTRADAY_ADVISER_V1_0'
),
ranked AS (
    SELECT
        b.*,
        ROW_NUMBER() OVER (
            PARTITION BY b.SYMBOL, b.TRADING_DATE
            ORDER BY
                CASE WHEN b.STATUS = 'COMPLETED' AND b.CALL_COUNT >= 1 THEN 1 ELSE 0 END DESC,
                b.TRADE_COUNT DESC,
                b.CALL_COUNT DESC,
                b.CREATED_AT DESC
        ) AS RN
    FROM base b
)
SELECT ADVISER_ATTEMPT_ID
FROM ranked
WHERE RN > 1
   OR (
        STATUS = 'RUNNING'
        AND EXISTS (
            SELECT 1
            FROM base b2
            WHERE b2.SYMBOL = ranked.SYMBOL
              AND b2.TRADING_DATE = ranked.TRADING_DATE
              AND b2.STATUS = 'COMPLETED'
              AND b2.CALL_COUNT >= 1
        )
   );

SELECT COUNT(*) AS ATTEMPTS_TO_DELETE FROM _ADVISER_V1_DEDUPE_LOSERS;

DELETE FROM MIP.APP.BROOKS_INTRADAY_ADVISER_SIM_TRADE t
WHERE t.ADVISER_ATTEMPT_ID IN (SELECT ADVISER_ATTEMPT_ID FROM _ADVISER_V1_DEDUPE_LOSERS);

DELETE FROM MIP.APP.BROOKS_INTRADAY_ADVISER_BAR b
WHERE b.ADVISER_ATTEMPT_ID IN (SELECT ADVISER_ATTEMPT_ID FROM _ADVISER_V1_DEDUPE_LOSERS);

DELETE FROM MIP.APP.BROOKS_INTRADAY_ADVISER_CALL c
WHERE c.ADVISER_ATTEMPT_ID IN (SELECT ADVISER_ATTEMPT_ID FROM _ADVISER_V1_DEDUPE_LOSERS);

DELETE FROM MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT s
WHERE s.CONTEXT_ATTEMPT_ID IN (SELECT ADVISER_ATTEMPT_ID FROM _ADVISER_V1_DEDUPE_LOSERS);

DELETE FROM MIP.APP.BROOKS_INTRADAY_ADVISER_ATTEMPT a
WHERE a.ADVISER_ATTEMPT_ID IN (SELECT ADVISER_ATTEMPT_ID FROM _ADVISER_V1_DEDUPE_LOSERS);

SELECT
    a.SYMBOL,
    a.TRADING_DATE,
    COUNT(*) AS ATTEMPT_COUNT
FROM MIP.APP.BROOKS_INTRADAY_ADVISER_ATTEMPT a
WHERE a.CONFIG_JSON:adviser_version::STRING = 'BROOKS_INTRADAY_ADVISER_V1_0'
  AND a.STATUS = 'COMPLETED'
GROUP BY 1, 2
HAVING COUNT(*) > 1;
