/*  ================================================================
    20260522_backfill_execution_policy_existing_rows.sql
    One-time remediation for existing STRUCTURAL_TRADE_PROPOSALS rows.

    Steps:
      1. NULL SETUP_EVENT_ID for existing rows where the evidence setup
         direction differs from the proposal direction, and mark them
         POLICY_BLOCKED / SETUP_EVENT_DIRECTION_MISMATCH.
      2. Run geometry validation against all existing EXECUTABLE rows
         (new rows get this automatically via the post-INSERT block
          in 566 and orchestrator.py; existing rows need it once).
    ================================================================ */

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;
USE WAREHOUSE MIP_WH_XS;

-- Step 1a: Count cross-direction rows before fix
SELECT 'BEFORE_FIX_CROSS_DIRECTION' AS LABEL,
       p.PROPOSAL_ID, p.DIRECTION AS PROPOSAL_DIR,
       se.DIRECTION AS EVIDENCE_DIR,
       p.SETUP_EVENT_ID, p.EXECUTION_POLICY_STATUS
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
JOIN MIP.APP.STRUCTURAL_SETUP_EVENTS se
  ON se.SETUP_EVENT_ID = p.SETUP_EVENT_ID
WHERE se.DIRECTION != p.DIRECTION
  AND p.BOARD_RUN_ID IS NOT NULL;

-- Step 1b: Null SETUP_EVENT_ID and mark POLICY_BLOCKED for cross-direction rows
UPDATE MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
   SET SETUP_EVENT_ID            = NULL,
       EXECUTION_POLICY_STATUS   = 'POLICY_BLOCKED',
       EXECUTION_POLICY_REASON   = 'SETUP_EVENT_DIRECTION_MISMATCH',
       IS_RESEARCH_ONLY          = TRUE
  FROM MIP.APP.STRUCTURAL_SETUP_EVENTS se
 WHERE se.SETUP_EVENT_ID  = p.SETUP_EVENT_ID
   AND se.DIRECTION       != p.DIRECTION
   AND p.BOARD_RUN_ID IS NOT NULL;

-- Step 2: Count geometry-invalid rows before fix (scoped to remaining EXECUTABLE)
SELECT 'BEFORE_FIX_GEOMETRY_INVALID' AS LABEL, DIRECTION, COUNT(*) AS COUNT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE COALESCE(EXECUTION_POLICY_STATUS, 'EXECUTABLE') = 'EXECUTABLE'
  AND (
      (DIRECTION = 'LONG'  AND PRICE_INVALIDATION_LEVEL IS NOT NULL
       AND ENTRY_ZONE_LOW IS NOT NULL AND PRICE_INVALIDATION_LEVEL >= ENTRY_ZONE_LOW)
      OR
      (DIRECTION = 'SHORT' AND PRICE_INVALIDATION_LEVEL IS NOT NULL
       AND ENTRY_ZONE_HIGH IS NOT NULL AND PRICE_INVALIDATION_LEVEL <= ENTRY_ZONE_HIGH)
      OR
      (ENTRY_ZONE_LOW IS NOT NULL AND ENTRY_ZONE_HIGH IS NOT NULL
       AND ENTRY_ZONE_LOW > ENTRY_ZONE_HIGH)
  )
GROUP BY DIRECTION;

-- Step 3: Apply geometry validation to all existing EXECUTABLE rows
UPDATE MIP.APP.STRUCTURAL_TRADE_PROPOSALS
   SET EXECUTION_POLICY_STATUS = 'GEOMETRY_INVALID',
       EXECUTION_POLICY_REASON = CASE
           WHEN DIRECTION = 'LONG'  THEN 'INVALID_LONG_GEOMETRY'
           WHEN DIRECTION = 'SHORT' THEN 'INVALID_SHORT_GEOMETRY'
           ELSE 'INVALID_LONG_GEOMETRY'
       END,
       IS_RESEARCH_ONLY = TRUE
 WHERE COALESCE(EXECUTION_POLICY_STATUS, 'EXECUTABLE') = 'EXECUTABLE'
   AND (
       (DIRECTION = 'LONG'  AND PRICE_INVALIDATION_LEVEL IS NOT NULL
        AND ENTRY_ZONE_LOW IS NOT NULL AND PRICE_INVALIDATION_LEVEL >= ENTRY_ZONE_LOW)
       OR
       (DIRECTION = 'SHORT' AND PRICE_INVALIDATION_LEVEL IS NOT NULL
        AND ENTRY_ZONE_HIGH IS NOT NULL AND PRICE_INVALIDATION_LEVEL <= ENTRY_ZONE_HIGH)
       OR
       (ENTRY_ZONE_LOW IS NOT NULL AND ENTRY_ZONE_HIGH IS NOT NULL
        AND ENTRY_ZONE_LOW > ENTRY_ZONE_HIGH)
   );

-- Step 4: Final status distribution
SELECT EXECUTION_POLICY_STATUS, EXECUTION_POLICY_REASON, DIRECTION, IS_RESEARCH_ONLY,
       COUNT(*) AS ROW_COUNT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
GROUP BY EXECUTION_POLICY_STATUS, EXECUTION_POLICY_REASON, DIRECTION, IS_RESEARCH_ONLY
ORDER BY ROW_COUNT DESC;
