-- One-time backfill: STRUCTURAL_PROPOSAL_SNAPSHOT for proposals created before Committee 2.0 DDL.
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE WAREHOUSE MIP_WH_XS;

INSERT INTO MIP.APP.STRUCTURAL_PROPOSAL_SNAPSHOT (
    PROPOSAL_ID, PROPOSAL_TS, SYMBOL, SIDE, SETUP_FAMILY,
    STRUCTURAL_STATE, REGIME_STATE, TRUST_LABEL,
    ENTRY_ZONE_JSON, INVALIDATION_JSON, PATH_METRICS_JSON, MFE_MAE_JSON,
    TRAILING_STYLE, PROPOSAL_SUMMARY_JSON
)
SELECT
    p.PROPOSAL_ID,
    p.CREATED_AT,
    p.SYMBOL,
    p.DIRECTION,
    p.SETUP_FAMILY,
    p.COMMITTEE_PAYLOAD:structural_state::STRING,
    p.REGIME_COMPAT,
    COALESCE(p.COMMITTEE_PAYLOAD:trust_label::STRING, 'UNKNOWN'),
    OBJECT_CONSTRUCT('low', p.ENTRY_ZONE_LOW, 'high', p.ENTRY_ZONE_HIGH),
    OBJECT_CONSTRUCT('level', p.PRICE_INVALIDATION_LEVEL, 'rule', p.INVALIDATION_RULE),
    OBJECT_CONSTRUCT(
        'meaningful_hit_rate', p.MEANINGFUL_HIT_RATE,
        'path_survival_hit_rate', p.PATH_SURVIVAL_HIT_RATE,
        'mfe_mae_ratio', p.MFE_MAE_RATIO,
        'median_mfe', p.COMMITTEE_PAYLOAD:median_mfe,
        'median_mae', p.COMMITTEE_PAYLOAD:median_mae,
        'pct_adverse_before_favorable', p.COMMITTEE_PAYLOAD:pct_adverse_before_favorable,
        'gap_risk', p.COMMITTEE_PAYLOAD:gap_risk
    ),
    OBJECT_CONSTRUCT(
        'mfe_mae_ratio', p.MFE_MAE_RATIO,
        'meaningful_hit_rate', p.MEANINGFUL_HIT_RATE,
        'path_survival_hit_rate', p.PATH_SURVIVAL_HIT_RATE
    ),
    p.TRAIL_STYLE,
    p.COMMITTEE_PAYLOAD
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
WHERE NOT EXISTS (
    SELECT 1 FROM MIP.APP.STRUCTURAL_PROPOSAL_SNAPSHOT s WHERE s.PROPOSAL_ID = p.PROPOSAL_ID
);

SELECT COUNT(*) AS SNAPSHOT_ROWS FROM MIP.APP.STRUCTURAL_PROPOSAL_SNAPSHOT;
