-- Kill hung BA shadow validation: stale RUNNING session stuck at stage 0.
UPDATE MIP.APP.SHADOW_BOARD_SESSION
   SET STATUS = 'FAILED',
       DEGRADED = TRUE,
       DEGRADED_REASON = 'OPERATOR_CANCELLED_HUNG_SESSION',
       COMPLETED_AT = CURRENT_TIMESTAMP(),
       RUN_MS = DATEDIFF('millisecond', CREATED_AT, CURRENT_TIMESTAMP())
 WHERE SESSION_ID = '84b7b92a-27c5-4fe0-926d-5839b46f7700'
   AND STATUS = 'RUNNING';

SELECT SESSION_ID, STATUS, STAGE_REACHED, DEGRADED_REASON, COMPLETED_AT
  FROM MIP.APP.SHADOW_BOARD_SESSION
 WHERE SESSION_ID = '84b7b92a-27c5-4fe0-926d-5839b46f7700';
