-- phase4_drop_cortex_agents.sql
-- Retire expensive Cortex Agent objects (uncapped tool-loop path).
-- Phase 4 runtime now uses bounded AI_COMPLETE calls only.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

DROP AGENT IF EXISTS MIP.APP.PHASE4_MARKET_STRUCTURE_AGENT;
DROP AGENT IF EXISTS MIP.APP.PHASE4_LEVEL_PRICE_ACTION_AGENT;
DROP AGENT IF EXISTS MIP.APP.PHASE4_THESIS_AGENT;
DROP AGENT IF EXISTS MIP.APP.PHASE4_HISTORICAL_EVIDENCE_AGENT;
DROP AGENT IF EXISTS MIP.APP.PHASE4_RISK_EXECUTION_AGENT;
DROP AGENT IF EXISTS MIP.APP.PHASE4_CHAIR_PORTFOLIO_PM_AGENT;
