/* ================================================================
   phase4_retire_single_completion_board_proposals.sql
   Retire active proposals produced by the rejected Phase 4 single-
   completion roleplay board (PROMPT_VERSION
   'proposal_board_v3_phase4_symbol_dossier_combined').

   These proposals were generated by ONE SNOWFLAKE.CORTEX.COMPLETE
   call per dossier that role-played all six "agent" sections inside
   one response. That violates the agentic requirement and is rejected.

   This script:
     * Expires those proposals with reason
       RETIRED_SINGLE_COMPLETION_ROLEPLAY_BOARD_NOT_TRUE_AGENTIC.
     * Supersedes any pre-broker MIP.LIVE.LIVE_ACTIONS rows linked
       to them.
     * PRESERVES all historical rows in PROPOSAL_BOARD_RUN,
       PROPOSAL_BOARD_SYMBOL_DOSSIER_SNAPSHOT,
       PROPOSAL_BOARD_AGENT_OUTCOME_V2,
       PROPOSAL_BOARD_THESIS_VERDICT,
       PROPOSAL_BOARD_FINAL_SLATE_V2,
       PROPOSAL_BOARD_OUTPUT_ERROR,
       STRUCTURAL_PROPOSAL_SNAPSHOT (audit only).
     * Does NOT touch executed trades, IBKR/live truth,
       reconciliation rows, or broker-submitted live actions
       (STATUS='EXECUTION_REQUESTED' or post-broker statuses).
   ================================================================ */

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE OR REPLACE TEMPORARY TABLE TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS AS
SELECT
    p.PROPOSAL_ID,
    p.SYMBOL,
    p.BOARD_RUN_ID,
    p.BOARD_DOSSIER_ID
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
JOIN MIP.APP.PROPOSAL_BOARD_RUN r
  ON r.RUN_ID = p.BOARD_RUN_ID
WHERE p.STATUS = 'PROPOSED'
  AND r.PROMPT_VERSION = 'proposal_board_v3_phase4_symbol_dossier_combined';

SELECT
    'BEFORE_RETIRE' AS STEP,
    COUNT(*) AS PROPOSALS_TO_EXPIRE,
    ARRAY_AGG(PROPOSAL_ID) WITHIN GROUP (ORDER BY PROPOSAL_ID) AS PROPOSAL_IDS,
    ARRAY_AGG(DISTINCT BOARD_RUN_ID) AS BOARD_RUN_IDS
FROM TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS;

UPDATE MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
   SET STATUS = 'EXPIRED',
       COMMITTEE_PAYLOAD = OBJECT_INSERT(
           OBJECT_INSERT(
               COALESCE(p.COMMITTEE_PAYLOAD, OBJECT_CONSTRUCT()),
               'phase4_single_completion_retired',
               OBJECT_CONSTRUCT(
                   'reason_code', 'RETIRED_SINGLE_COMPLETION_ROLEPLAY_BOARD_NOT_TRUE_AGENTIC',
                   'retired_at', CURRENT_TIMESTAMP(),
                   'preserved_board_run_id', p.BOARD_RUN_ID,
                   'preserved_board_dossier_id', p.BOARD_DOSSIER_ID,
                   'historical_row_preserved', TRUE,
                   'rejected_implementation', 'one_snowflake_cortex_complete_call_per_dossier_returning_six_role_sections_plus_chair_in_one_json'
               ),
               TRUE
           ),
           'status_before_phase4_agentic_rebuild',
           'PROPOSED',
           TRUE
       ),
       BOARD_PAYLOAD_JSON = OBJECT_INSERT(
           COALESCE(p.BOARD_PAYLOAD_JSON, OBJECT_CONSTRUCT()),
           'phase4_single_completion_retired',
           OBJECT_CONSTRUCT(
               'reason_code', 'RETIRED_SINGLE_COMPLETION_ROLEPLAY_BOARD_NOT_TRUE_AGENTIC',
               'retired_at', CURRENT_TIMESTAMP(),
               'historical_row_preserved', TRUE
           ),
           TRUE
       )
 WHERE p.PROPOSAL_ID IN (
     SELECT PROPOSAL_ID FROM TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS
 );

UPDATE MIP.LIVE.LIVE_ACTIONS la
   SET STATUS = 'SUPERSEDED',
       REASON_CODES = ARRAY_APPEND(
           COALESCE(la.REASON_CODES, ARRAY_CONSTRUCT()),
           'RETIRED_SINGLE_COMPLETION_ROLEPLAY_BOARD_NOT_TRUE_AGENTIC'
       ),
       UPDATED_AT = CURRENT_TIMESTAMP()
 WHERE la.LIVE_INTENT_KIND = 'STRUCTURAL'
   AND la.PROPOSAL_ID IN (
       SELECT PROPOSAL_ID FROM TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS
   )
   AND la.STATUS IN (
       'PROPOSED',
       'INTENT_APPROVED',
       'PENDING_OPEN_VALIDATION',
       'OPEN_BLOCKED'
   );

SELECT
    'AFTER_RETIRE' AS STEP,
    (SELECT COUNT(*) FROM TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS) AS PROPOSALS_EXPIRED,
    (SELECT COUNT(*)
       FROM MIP.LIVE.LIVE_ACTIONS la
      WHERE la.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS)
        AND la.STATUS = 'SUPERSEDED'
        AND ARRAY_CONTAINS('RETIRED_SINGLE_COMPLETION_ROLEPLAY_BOARD_NOT_TRUE_AGENTIC'::VARIANT, la.REASON_CODES)
    ) AS PRE_BROKER_ACTIONS_SUPERSEDED,
    (SELECT COUNT(*)
       FROM MIP.LIVE.LIVE_ACTIONS la
      WHERE la.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS)
        AND la.STATUS = 'EXECUTION_REQUESTED'
    ) AS BROKER_SUBMITTED_ACTIONS_LEFT_UNCHANGED,
    (SELECT COUNT(*)
       FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
       JOIN MIP.APP.PROPOSAL_BOARD_RUN r ON r.RUN_ID = p.BOARD_RUN_ID
      WHERE p.STATUS = 'PROPOSED'
        AND r.PROMPT_VERSION = 'proposal_board_v3_phase4_symbol_dossier_combined'
    ) AS REMAINING_ACTIVE_SINGLE_COMPLETION_PROPOSALS;

DROP TABLE IF EXISTS TMP_PHASE4_RETIRED_SINGLE_COMPLETION_PROPOSALS;
