-- Restore BA submit gate: operator APPROVE_REDUCED was displaced by AUTO_AUDIT DEFER
-- rows from re-runs where SHADOW_CHAIR returned empty JSON (parse failure).
UPDATE MIP.APP.AGENTIC_REVALIDATION_AUTHORITY
   SET IS_LATEST = FALSE,
       UPDATED_AT = CURRENT_TIMESTAMP()
 WHERE ACTION_ID = 'a195f542-bdc4-4a89-a951-207015153652'
   AND IS_LATEST = TRUE;

UPDATE MIP.APP.AGENTIC_REVALIDATION_AUTHORITY
   SET IS_LATEST = TRUE,
       SUPERSEDED_AT = NULL,
       SUPERSEDED_BY = NULL,
       UPDATED_AT = CURRENT_TIMESTAMP()
 WHERE AUTHORITY_ID = '6e148eb6-aa35-4d89-a680-ef60f1b323ab';

SELECT AUTHORITY_ID, AUTHORITY_MODE, AUTHORITY_STATUS, IS_LATEST, SHADOW_SESSION_ID
  FROM MIP.APP.AGENTIC_REVALIDATION_AUTHORITY
 WHERE ACTION_ID = 'a195f542-bdc4-4a89-a951-207015153652'
   AND IS_LATEST = TRUE;

SELECT ACTION_ID, SYMBOL, STATUS, REASON_CODES
  FROM MIP.LIVE.LIVE_ACTIONS
 WHERE ACTION_ID = 'a195f542-bdc4-4a89-a951-207015153652';
