# IMPORTANT: No business logic here. All analytics live in SQL (MIP.MART/MIP.APP). Python is UI-only.
"""Minimal Streamlit UI skeleton for the MIP application."""

import streamlit as st
from snowflake.snowpark.context import get_active_session
from snowflake.snowpark.exceptions import SnowparkSQLException


def get_session():
    """Return the active Snowflake session provided by Streamlit deployments."""
    return get_active_session()


def show_market_overview(session):
    st.header("Market Overview")
    query = "SELECT * FROM MIP.MART.FX_TICKS LIMIT 50"
    data = session.sql(query).to_pandas()
    st.dataframe(data, use_container_width=True)


def show_patterns_and_learning(session):
    st.header("Patterns & Learning")
    query = "SELECT * FROM MIP.APP.PATTERN_DEFINITION LIMIT 50"
    try:
        data = session.sql(query).to_pandas()
    except SnowparkSQLException:
        st.warning(
            "Pattern definitions are not available yet. "
            "This page will populate once MIP.APP.PATTERN_DEFINITION exists."
        )
        return
    st.dataframe(data, use_container_width=True)


def show_signals_and_recommendations():
    st.header("Signals & Recommendations")
    st.info(
        "Signals and recommendations will be generated by stored procedures in MIP.APP "
        "and logged into MIP.APP.RECOMMENDATION_LOG. "
        "This UI will display those results once they are available."
    )


def show_outcome_evaluation():
    st.header("Outcome Evaluation")
    st.info(
        "Outcome evaluations will be sourced from MIP.APP.OUTCOME_EVALUATION. "
        "Visualizations and analytics will be added here once the table is populated."
    )


def main():
    st.set_page_config(page_title="MIP", layout="wide")
    st.title("Market Intelligence Platform")

    st.sidebar.title("Navigation")
    pages = {
        "Market Overview": (show_market_overview, True),
        "Patterns & Learning": (show_patterns_and_learning, True),
        "Signals & Recommendations": (show_signals_and_recommendations, False),
        "Outcome Evaluation": (show_outcome_evaluation, False),
    }

    selected_page = st.sidebar.radio("Go to", list(pages.keys()))

    render_fn, requires_session = pages[selected_page]
    session = get_session() if requires_session else None

    if requires_session:
        render_fn(session)
    else:
        render_fn()


if __name__ == "__main__":
    main()
