-- =============================================================
-- MIP Infrastructure Bootstrap Script
-- =============================================================

-- ===============================
-- Database and Schema Definitions
-- ===============================
CREATE DATABASE IF NOT EXISTS MIP;

CREATE SCHEMA IF NOT EXISTS MIP.RAW_EXT;
CREATE SCHEMA IF NOT EXISTS MIP.MART;
CREATE SCHEMA IF NOT EXISTS MIP.APP;
CREATE SCHEMA IF NOT EXISTS MIP.AGENT_OUT;

-- ===============================
-- Warehouse Definitions
-- ===============================
CREATE WAREHOUSE IF NOT EXISTS MIP_WH_XS
  WITH WAREHOUSE_SIZE = XSMALL
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS MIP_WH_S
  WITH WAREHOUSE_SIZE = SMALL
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE;

-- ===============================
-- Role Definitions
-- ===============================
CREATE ROLE IF NOT EXISTS MIP_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS MIP_APP_ROLE;
CREATE ROLE IF NOT EXISTS MIP_AGENT_READ_ROLE;

-- ===============================
-- Role Grants on Databases and Schemas
-- ===============================
GRANT ALL PRIVILEGES ON DATABASE MIP TO ROLE MIP_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE MIP TO ROLE MIP_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE MIP TO ROLE MIP_ADMIN_ROLE;

GRANT USAGE ON DATABASE MIP TO ROLE MIP_APP_ROLE;
GRANT USAGE ON SCHEMA MIP.MART TO ROLE MIP_APP_ROLE;
GRANT USAGE ON SCHEMA MIP.APP TO ROLE MIP_APP_ROLE;
GRANT USAGE ON SCHEMA MIP.AGENT_OUT TO ROLE MIP_APP_ROLE;

-- ===============================
-- Role Grants on Warehouses
-- ===============================
GRANT USAGE ON WAREHOUSE MIP_WH_XS TO ROLE MIP_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE MIP_WH_S TO ROLE MIP_ADMIN_ROLE;
GRANT OPERATE ON WAREHOUSE MIP_WH_XS TO ROLE MIP_ADMIN_ROLE;
GRANT OPERATE ON WAREHOUSE MIP_WH_S TO ROLE MIP_ADMIN_ROLE;

GRANT USAGE ON WAREHOUSE MIP_WH_XS TO ROLE MIP_APP_ROLE;

-- ===============================
-- External Data Sharing Grants
-- ===============================
GRANT IMPORTED PRIVILEGES ON DATABASE PUBLIC_DOMAIN_DATA TO ROLE MIP_ADMIN_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE PUBLIC_DOMAIN_DATA TO ROLE MIP_APP_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE PUBLIC_DOMAIN_DATA TO ROLE MIP_AGENT_READ_ROLE;

GRANT IMPORTED PRIVILEGES ON DATABASE TRADERMADE_CURRENCY_EXCHANGE_RATES TO ROLE MIP_ADMIN_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE TRADERMADE_CURRENCY_EXCHANGE_RATES TO ROLE MIP_APP_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE TRADERMADE_CURRENCY_EXCHANGE_RATES TO ROLE MIP_AGENT_READ_ROLE;
