-- Source: TRADERMADE_CURRENCY_EXCHANGE_RATES.PUBLIC.TICK_DATA_SAMPLE
-- Purpose: simple, generic FX tick view for the Market Intelligence Platform.

CREATE OR REPLACE VIEW MIP.MART.FX_TICKS AS
SELECT
    CAST(TIME AS TIMESTAMP_NTZ) AS TS,
    INST                        AS PAIR,
    BID,
    ASK,
    (ASK + BID) / 2             AS MID_PRICE,
    ASK - BID                   AS SPREAD
FROM TRADERMADE_CURRENCY_EXCHANGE_RATES.PUBLIC.TICK_DATA_SAMPLE;

COMMENT ON COLUMN MIP.MART.FX_TICKS.TS IS 'Tick timestamp (TIMESTAMP_NTZ).';
COMMENT ON COLUMN MIP.MART.FX_TICKS.PAIR IS 'FX instrument pair (e.g. EURUSD).';
COMMENT ON COLUMN MIP.MART.FX_TICKS.BID IS 'Quoted bid price.';
COMMENT ON COLUMN MIP.MART.FX_TICKS.ASK IS 'Quoted ask price.';
COMMENT ON COLUMN MIP.MART.FX_TICKS.MID_PRICE IS 'Midpoint between BID and ASK.';
COMMENT ON COLUMN MIP.MART.FX_TICKS.SPREAD IS 'ASK - BID.';
