-- Source: TRADERMADE_CURRENCY_EXCHANGE_RATES.PUBLIC.TICK_DATA_SAMPLE
-- Purpose: simple, generic FX tick view for the Market Intelligence Platform.

CREATE OR REPLACE VIEW MIP.MART.FX_TICKS AS
SELECT
    CAST(TIME AS TIMESTAMP_NTZ) AS TS,
    INST                        AS PAIR,
    BID,
    ASK,
    (ASK + BID) / 2             AS MID_PRICE,
    ASK - BID                   AS SPREAD
FROM TRADERMADE_CURRENCY_EXCHANGE_RATES.PUBLIC.TICK_DATA_SAMPLE;
