"""Brooks Intraday Lab constants and isolation boundary markers."""

SIMULATION_BANNER = "SIMULATION ONLY — NO REAL ORDERS OR PORTFOLIO CONNECTION"

DEFAULT_PILOT_SYMBOLS = ("AAPL", "AMZN", "JPM", "MCD")

RULESET_VERSION_DEFAULT = "BROOKS_RULESET_V0_1"
DOSSIER_VERSION_DEFAULT = "PAA_INTRADAY_DOSSIER_V0_1"
COMPILER_VERSION_DEFAULT = "BROOKS_DOSSIER_COMPILER_V0_1"
RECONSTRUCTION_VERSION_DEFAULT = "BROOKS_PAA_RECONSTRUCTION_V0_1"
RECONSTRUCTION_PROMPT_VERSION_DEFAULT = "BROOKS_PAA_RECONSTRUCTION_PROMPT_V0_1"
TIE_BREAK_VERSION_DEFAULT = "BROOKS_TIEBREAK_V0_1"

EXPECTED_RTH_5M_BARS_FULL_SESSION = 78
DEFAULT_PAA_LOOKBACK_BARS = 120

IMMUTABLE_RUN_STATUSES = frozenset(
    {"READY", "RUNNING", "PAUSED", "STOPPED", "COMPLETED", "PREPARATION_FAILED"}
)

DEFAULT_STARTING_CASH = 1000.0
DEFAULT_MODE = "HISTORICAL_REPLAY"

# Modules this package must never import or call (documentation + guard tests).
FORBIDDEN_INTEGRATION_PREFIXES = (
    "app.routers.live",
    "app.routers.agentic_authority",
    "ib_insync",
)
