"""BROOKS_CONTEXT_RULESET_V0_1 — Phase 6 PAA thesis alignment and advisory state machine."""

from __future__ import annotations

RULESET_VERSION = "BROOKS_CONTEXT_RULESET_V0_1"

# Advisory states (no open position)
STATE_DOSSIER_READY = "DOSSIER_READY"
STATE_OBSERVING_OPEN = "OBSERVING_OPEN"
STATE_WAITING_FOR_PULLBACK = "WAITING_FOR_PULLBACK"
STATE_WAITING_FOR_SUPPORT_TEST = "WAITING_FOR_SUPPORT_TEST"
STATE_WAITING_FOR_NEW_SETUP = "WAITING_FOR_NEW_SETUP"
STATE_WAITING_FOR_RTH_CONFIRMATION = "WAITING_FOR_RTH_CONFIRMATION"
STATE_WAITING_FOR_STRONGER_CONFIRMATION = "WAITING_FOR_STRONGER_CONFIRMATION"
STATE_SETUP_DEVELOPING = "SETUP_DEVELOPING"
STATE_WAITING_FOR_RECLAIM = "WAITING_FOR_RECLAIM"
STATE_WAITING_FOR_FOLLOW_THROUGH = "WAITING_FOR_FOLLOW_THROUGH"
STATE_ENTRY_ARMED = "ENTRY_ARMED"
STATE_ENTRY_BLOCKED = "ENTRY_BLOCKED"
STATE_DO_NOT_CHASE = "DO_NOT_CHASE"
STATE_THESIS_WEAKENED = "THESIS_WEAKENED"
STATE_THESIS_INVALIDATED = "THESIS_INVALIDATED"
STATE_OBSERVATION_ONLY = "OBSERVATION_ONLY"
STATE_DONE = "DONE"

# Actions
ACTION_OBSERVE = "OBSERVE"
ACTION_WAIT = "WAIT"
ACTION_WAIT_FOR_PULLBACK = "WAIT_FOR_PULLBACK"
ACTION_WAIT_FOR_SUPPORT = "WAIT_FOR_SUPPORT"
ACTION_WAIT_FOR_RECLAIM = "WAIT_FOR_RECLAIM"
ACTION_WAIT_FOR_FOLLOW_THROUGH = "WAIT_FOR_FOLLOW_THROUGH"
ACTION_WAIT_FOR_NEW_SETUP = "WAIT_FOR_NEW_SETUP"
ACTION_ENTRY_ARMED = "ENTRY_ARMED"
ACTION_CONSIDER_ENTRY = "CONSIDER_ENTRY"
ACTION_HOLD_POSITION = "HOLD_POSITION"
ACTION_DO_NOT_CHASE = "DO_NOT_CHASE"
ACTION_DO_NOT_ENTER = "DO_NOT_ENTER"
ACTION_THESIS_WEAKENED = "THESIS_WEAKENED"
ACTION_THESIS_INVALIDATED = "THESIS_INVALIDATED"

# Thesis effect
EFFECT_CONFIRMS = "CONFIRMS"
EFFECT_SLIGHTLY_CONFIRMS = "SLIGHTLY_CONFIRMS"
EFFECT_NEUTRAL = "NEUTRAL"
EFFECT_SLIGHTLY_WEAKENS = "SLIGHTLY_WEAKENS"
EFFECT_WEAKENS = "WEAKENS"
EFFECT_INVALIDATES = "INVALIDATES"

# Reclaim stages
RECLAIM_BELOW = "BELOW_RECLAIM"
RECLAIM_TESTING = "TESTING_RECLAIM"
RECLAIM_CLOSED_ABOVE = "CLOSED_ABOVE_RECLAIM"
RECLAIM_CONFIRMED = "RECLAIM_CONFIRMED"
RECLAIM_FAILED = "RECLAIM_FAILED"

# Support interaction
SUPPORT_ABOVE = "ABOVE_SUPPORT"
SUPPORT_APPROACHING = "APPROACHING_SUPPORT"
SUPPORT_TESTING = "TESTING_SUPPORT"
SUPPORT_HELD = "SUPPORT_HELD"
SUPPORT_PIERCED = "SUPPORT_PIERCED"
SUPPORT_FAILED = "SUPPORT_FAILED"

# Room
ROOM_AMPLE = "AMPLE_ROOM"
ROOM_ACCEPTABLE = "ACCEPTABLE_ROOM"
ROOM_LIMITED = "LIMITED_ROOM"
ROOM_AT_RESISTANCE = "AT_RESISTANCE"
ROOM_ABOVE_DNC = "ABOVE_DO_NOT_CHASE"

# Invalidation types (Phase 6 uses first two only)
INV_DAILY_THESIS = "DAILY_THESIS_INVALIDATION"
INV_INTRADAY_SETUP = "INTRADAY_SETUP_INVALIDATION"
INV_SIM_STOP = "SIMULATED_TRADE_STOP"  # Phase 7 only — never used as stop in Phase 6

DEFAULT_PARAMETERS: dict[str, object] = {
    "opening_observation_bars": 3,
    "support_proximity_fraction": 0.15,
    "resistance_proximity_fraction": 0.12,
    "reclaim_confirm_bars": 2,
    "reclaim_min_close_quality_fraction": 0.55,
    "do_not_chase_buffer_fraction": 0.02,
    "stale_pattern_bars": 18,
    "min_room_acceptable_fraction": 0.35,
    "min_room_ample_fraction": 0.55,
    "thesis_weaken_close_below_support_ticks": 2,
    "verdict_initial_state": {
        "WAIT_PULLBACK": STATE_WAITING_FOR_PULLBACK,
        "LONG_APPROVE": STATE_WAITING_FOR_RTH_CONFIRMATION,
        "LONG_APPROVE_REDUCED": STATE_WAITING_FOR_STRONGER_CONFIRMATION,
        "NO_CLEAR_LONG": STATE_OBSERVATION_ONLY,
        "DEFAULT": STATE_OBSERVATION_ONLY,
    },
    "verdict_initial_action": {
        "WAIT_PULLBACK": ACTION_WAIT_FOR_PULLBACK,
        "LONG_APPROVE": ACTION_WAIT,
        "LONG_APPROVE_REDUCED": ACTION_WAIT,
        "NO_CLEAR_LONG": ACTION_OBSERVE,
        "DEFAULT": ACTION_OBSERVE,
    },
    "pattern_significance_entry_capable": [
        "STRUCTURAL_DOUBLE_BOTTOM",
        "LOCAL_DOUBLE_BOTTOM",
        "POSSIBLE_H2_LONG",
        "H2_LONG",
        "CONFIRMED_H2_LONG",
        "TWO_LEGGED_PULLBACK",
        "CONFIRMED_WEDGE_BOTTOM",
        "STRUCTURAL_BREAKOUT",
        "FAILED_BEAR_BREAKOUT",
        "BULL_MICRO_CHANNEL",
    ],
    "pattern_significance_observation_only": [
        "MICRO_DOUBLE_BOTTOM",
        "LOCAL_PIVOT_LOW",
        "LOCAL_PIVOT_HIGH",
        "STRUCTURAL_SWING_LOW",
        "STRUCTURAL_SWING_HIGH",
        "POSSIBLE_H1_LONG",
        "FAILED_H1_LONG",
        "POSSIBLE_BUY_CLIMAX",
        "POSSIBLE_SELL_CLIMAX",
    ],
    "local_double_bottom_requires_reclaim_near": True,
    "action_precedence": [
        "DATA_ERROR",
        "THESIS_INVALIDATED",
        "DO_NOT_ENTER",
        "DO_NOT_CHASE",
        "ENTRY_BLOCKED",
        "THESIS_WEAKENED",
        "CONSIDER_ENTRY",
        "ENTRY_ARMED",
        "WAIT_FOR_FOLLOW_THROUGH",
        "WAIT_FOR_RECLAIM",
        "WAIT_FOR_SUPPORT",
        "WAIT_FOR_PULLBACK",
        "WAIT",
        "OBSERVE",
    ],
}


def resolve_params(overrides: dict | None = None) -> dict[str, object]:
    base = dict(DEFAULT_PARAMETERS)
    if overrides:
        base.update(overrides)
    return base
