"""Registry of Brooks Lab pipeline stages and Snowflake touchpoints (documentation + /meta)."""

from __future__ import annotations

from typing import Any

# Stage classification for retirement / Adviser path planning.
CLASS_RETAINED = "RETAINED"
CLASS_DIAGNOSTIC_LEGACY = "DIAGNOSTIC_LEGACY"
CLASS_ADVISER_FUTURE = "ADVISER_FUTURE"
CLASS_READ_ONLY_HISTORY = "READ_ONLY_HISTORY"


def snowflake_object_inventory() -> list[dict[str, Any]]:
    """Static inventory — no DROP/ALTER; drives cleanup proposals and /meta."""
    return [
        _row(
            "MIP.APP.BROOKS_INTRADAY_HISTORICAL_BAR",
            "Frozen 5m OHLCV for replay",
            lv=True,
            replay_write="prepare / IB acquisition",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_RUN",
            "Run header + CONFIG_JSON",
            lv=True,
            replay_write="create_run, pin updates (legacy sim only)",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_DOSSIER",
            "Daily frozen PAA pack per symbol/session",
            lv=True,
            replay_write="prepare / dossier reconstruction",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_REPLAY_STATE",
            "Interactive replay cursor",
            lv=False,
            replay_write="bar-at-a-time replay",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT",
            "Objective replay attempt metadata",
            lv=True,
            replay_write="objective bulk + next-bar (objective ruleset)",
            adviser="reuse reads; bulk optional",
            legacy="bulk only",
            stop_write="foundation: stop objective bulk",
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION",
            "Phase 4 objective bar observations",
            lv=True,
            replay_write="objective bulk + next-bar",
            adviser="cheap obs reuse candidate",
            legacy=False,
            stop_write="stop bulk; keep incremental",
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE",
            "Phase 5 pattern lifecycle state",
            lv=True,
            replay_write="pattern bulk + pattern next-bar",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later=True,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_BAR_PATTERN_LINK",
            "Per-bar active pattern links",
            lv=True,
            replay_write="pattern bulk + pattern next-bar",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later=True,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT",
            "Context replay attempt header",
            lv=True,
            replay_write="context bulk V0.1–V0.4",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later="attempt rows only after Adviser cutover",
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION",
            "Phase 6/6B context FSM snapshots",
            lv=True,
            replay_write="context bulk (largest insert volume)",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later=True,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT",
            "Simulation attempt header",
            lv=True,
            replay_write="simulation bulk / PM cert replay",
            adviser=True,
            legacy="context-driven bulk",
            stop_write="stop legacy context-linked bulk",
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_SIM_TRADE",
            "Trade ledger",
            lv=True,
            replay_write="simulation bulk",
            adviser=True,
            legacy=False,
            stop_write="stop new legacy sim bulk",
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL",
            "Blocked entry audit",
            lv=True,
            replay_write="simulation bulk",
            adviser=True,
            legacy=False,
            stop_write="stop new legacy sim bulk",
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_EXPERIMENT_EXECUTION",
            "Phase 9 orchestration",
            lv=False,
            replay_write="phase 9 ticks",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later=True,
        ),
        _row(
            "MIP.APP.BROOKS_EXPERIMENT_STAGE",
            "Phase 9 stage state",
            lv=False,
            replay_write="phase 9",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later=True,
        ),
        _row(
            "MIP.APP.BROOKS_EXPERIMENT_EVENT",
            "Phase 9 event log",
            lv=False,
            replay_write="phase 9",
            adviser=False,
            legacy=True,
            stop_write=True,
            ro=True,
            removable_later=True,
        ),
        _row(
            "MIP.KNOWLEDGE.LITERATURE_CONCEPT_CARD",
            "Brooks literature cards",
            lv=False,
            replay_write=False,
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.KNOWLEDGE.LITERATURE_RAG_DOCUMENT",
            "RAG corpus rows",
            lv=False,
            replay_write="SP_REFRESH only (manual)",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.KNOWLEDGE.LITERATURE_REVALIDATION_SEARCH_SERVICE",
            "Cortex Search service",
            lv=False,
            replay_write="indexing on refresh",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.KNOWLEDGE.LITERATURE_RAG_RETRIEVAL_AUDIT",
            "RAG call audit (future Adviser)",
            lv=False,
            replay_write="SP_SEARCH / Adviser wakes",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=True,
            removable_later=False,
        ),
        _row(
            "MIP.APP.BROOKS_INTRADAY_ADVISER_AUDIT",
            "Adviser thesis / watch audit (not deployed)",
            lv=True,
            replay_write="future Adviser",
            adviser=True,
            legacy=False,
            stop_write=False,
            ro=False,
            removable_later=False,
        ),
    ]


def pipeline_stages() -> list[dict[str, Any]]:
    return [
        {
            "stage": "historical_bars",
            "classification": CLASS_RETAINED,
            "rulesets": [],
            "python": ["acquisition", "historical_bar_repository"],
        },
        {
            "stage": "dossier_frozen_paa",
            "classification": CLASS_RETAINED,
            "rulesets": ["PAA_INTRADAY_DOSSIER_V0_1"],
            "python": ["dossier", "repository"],
        },
        {
            "stage": "bar_at_a_time_objective_replay",
            "classification": CLASS_RETAINED,
            "rulesets": ["BROOKS_RULESET_V0_1", "BROOKS_OBJECTIVE_RULESET_V0_1"],
            "python": ["replay_engine.process_next_bar"],
        },
        {
            "stage": "phase4_objective_bulk",
            "classification": CLASS_DIAGNOSTIC_LEGACY,
            "rulesets": ["BROOKS_OBJECTIVE_RULESET_V0_1"],
            "python": ["replay_engine.run_objective_replay_bulk"],
        },
        {
            "stage": "phase5_pattern_bulk",
            "classification": CLASS_DIAGNOSTIC_LEGACY,
            "rulesets": [
                "BROOKS_PATTERN_RULESET_V0_1",
                "BROOKS_PATTERN_RULESET_V0_2",
                "BROOKS_PATTERN_RULESET_V0_3",
            ],
            "python": ["replay_engine.run_pattern_replay_bulk"],
        },
        {
            "stage": "phase6_context_bulk",
            "classification": CLASS_DIAGNOSTIC_LEGACY,
            "rulesets": [
                "BROOKS_CONTEXT_RULESET_V0_1",
                "BROOKS_CONTEXT_RULESET_V0_2",
                "BROOKS_CONTEXT_RULESET_V0_3",
                "BROOKS_CONTEXT_RULESET_V0_4",
            ],
            "python": ["context_replay.run_context_replay_bulk"],
        },
        {
            "stage": "phase7_simulation_bulk",
            "classification": CLASS_DIAGNOSTIC_LEGACY,
            "rulesets": [
                "BROOKS_SIMULATION_RULESET_V0_1",
                "BROOKS_POSITION_MANAGEMENT_RULESET_V0_1",
            ],
            "python": ["simulation_replay.run_simulation_replay_bulk"],
        },
        {
            "stage": "learning_view",
            "classification": CLASS_RETAINED,
            "rulesets": [],
            "python": ["learning_view", "learning_bar_narrative"],
        },
        {
            "stage": "adviser_observation_builder",
            "classification": CLASS_ADVISER_FUTURE,
            "rulesets": ["BROOKS_INTRADAY_ADVISER_V1_0"],
            "python": ["(not implemented)"],
        },
        {
            "stage": "adviser_rag_wake",
            "classification": CLASS_ADVISER_FUTURE,
            "rulesets": [],
            "python": ["KNOWLEDGE.SP_SEARCH_REVALIDATION_LITERATURE"],
        },
    ]


def compute_hotspots() -> list[dict[str, str]]:
    """Qualitative warehouse load ordering for full-week legacy replay (~1,560 schedule steps)."""
    return [
        {
            "rank": "1",
            "stage": "context bulk V0.2–V0.4",
            "reason": "Per bar × symbol CONTEXT_OBSERVATION inserts + Python FSM; dominates wall time and WH credits.",
        },
        {
            "rank": "2",
            "stage": "pattern bulk V0.3",
            "reason": "PATTERN_INSTANCE upserts + BAR_PATTERN_LINK batched writes every bar.",
        },
        {
            "rank": "3",
            "stage": "objective bulk",
            "reason": "BAR_OBSERVATION inserts; smaller than pattern+context but still ~O(bars×symbols).",
        },
        {
            "rank": "4",
            "stage": "simulation bulk",
            "reason": "Reads context stream; fewer rows written (trades/blocks) but long CPU loop.",
        },
        {
            "rank": "5",
            "stage": "historical bar load / dossier",
            "reason": "One-time per week prepare; not per replay chain.",
        },
    ]


def _row(
    name: str,
    purpose: str,
    *,
    lv: bool,
    replay_write: Any,
    adviser: Any,
    legacy: Any,
    stop_write: Any,
    ro: bool,
    removable_later: Any,
) -> dict[str, Any]:
    return {
        "object": name,
        "purpose": purpose,
        "learning_view_reads": lv,
        "written_during_replay": replay_write,
        "needed_by_adviser": adviser,
        "legacy_diagnostic_only": legacy,
        "safe_to_stop_writing": stop_write,
        "safe_retain_read_only": ro,
        "candidate_later_removal": removable_later,
    }
