-- Phase 2: deterministic public disclosure context (symbol-mapped rows only).
-- API read path; no engine / stance integration.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

CREATE TABLE IF NOT EXISTS MIP.APP.PUBLIC_DISCLOSURE_TRANSACTION (
  DISCLOSURE_ID NUMBER(38,0) IDENTITY(1,1),
  SOURCE_URL VARCHAR(2000),
  SOURCE_NAME VARCHAR(256),
  DISCLOSURE_DATE DATE NOT NULL,
  PERSON_NAME VARCHAR(256),
  CHAMBER VARCHAR(64),
  TRANSACTION_TYPE VARCHAR(64),
  ASSET_SYMBOL VARCHAR(32),
  ASSET_CLASS VARCHAR(64),
  NOTIONAL_RANGE VARCHAR(128),
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PUBLIC_DISCLOSURE_TRANSACTION PRIMARY KEY (DISCLOSURE_ID)
);

COMMENT ON TABLE MIP.APP.PUBLIC_DISCLOSURE_TRANSACTION IS
  'Curated public trade/disclosure filings mapped to ASSET_SYMBOL for Committee 2.0 context card (Phase 2).';

GRANT SELECT ON TABLE MIP.APP.PUBLIC_DISCLOSURE_TRANSACTION TO ROLE MIP_UI_API_ROLE;

MERGE INTO MIP.APP.APP_CONFIG t
USING (
    SELECT 'COMMITTEE2_CONTEXT_DISCLOSURE_ENABLED' AS CONFIG_KEY,
           'false' AS CONFIG_VALUE,
           'When true, hearing payloads include exhibit_public_disclosure_context (Phase 2).' AS DESCRIPTION
) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_AT)
VALUES (s.CONFIG_KEY, s.CONFIG_VALUE, s.DESCRIPTION, CURRENT_TIMESTAMP());

SELECT CONFIG_KEY, CONFIG_VALUE FROM MIP.APP.APP_CONFIG WHERE CONFIG_KEY = 'COMMITTEE2_CONTEXT_DISCLOSURE_ENABLED';
