/* Simulation re-run clears prior rows — MIP_UI_API_ROLE needs DELETE */
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

GRANT DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL TO ROLE MIP_UI_API_ROLE;
GRANT DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_SIM_TRADE TO ROLE MIP_UI_API_ROLE;
