/* Brooks Intraday Lab — Phase 7 simulation attempt header */
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT (
    SIMULATION_ATTEMPT_ID     VARCHAR(36)   NOT NULL,
    RUN_ID                    VARCHAR(36)   NOT NULL,
    CONTEXT_ATTEMPT_ID        VARCHAR(36)   NOT NULL,
    CONTEXT_RULESET_VERSION   VARCHAR(128)  NOT NULL,
    SIMULATION_RULESET_VERSION VARCHAR(128) NOT NULL,
    STATUS                    VARCHAR(32)   NOT NULL,
    STARTING_CASH             NUMBER(18, 2),
    ENDING_CASH               NUMBER(18, 2),
    REALIZED_PNL              NUMBER(18, 4),
    TRADE_COUNT               NUMBER,
    BLOCKED_SIGNAL_COUNT      NUMBER,
    SEQUENCE_HASH             VARCHAR(128),
    NOTES                     VARCHAR(2000),
    CREATED_AT_UTC            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT_UTC          TIMESTAMP_NTZ,
    PRIMARY KEY (SIMULATION_ATTEMPT_ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT TO ROLE MIP_ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_SIM_TRADE TO ROLE MIP_ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL TO ROLE MIP_ADMIN_ROLE;

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT TO ROLE MIP_UI_API_ROLE;
