-- Brooks Intraday Lab Phase 3: persistent replay cursor (optional mirror; primary cursor in CONFIG_JSON)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_REPLAY_STATE (
    RUN_ID                VARCHAR(36)   NOT NULL PRIMARY KEY,
    REPLAY_CURSOR_JSON    VARIANT       NOT NULL,
    UPDATED_AT_UTC        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE MIP.APP.BROOKS_INTRADAY_REPLAY_STATE IS
    'Persistent Brooks Intraday replay cursor mirror. Authoritative copy also stored on BROOKS_INTRADAY_RUN.CONFIG_JSON.replay_cursor.';

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_REPLAY_STATE TO ROLE MIP_UI_API_ROLE;
