-- Committee 2.0: APP_CONFIG flag + grants for MIP_UI_API_ROLE (hearing CRUD).
-- Run after MIP/SQL/app/540_committee2_tables.sql and SP redeploy.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

MERGE INTO MIP.APP.APP_CONFIG t
USING (
    SELECT 'COMMITTEE2_ENABLED' AS CONFIG_KEY,
           'true' AS CONFIG_VALUE,
           'When true, Committee 2.0 structural hearing room API is enabled.' AS DESCRIPTION
) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_AT)
VALUES (s.CONFIG_KEY, s.CONFIG_VALUE, s.DESCRIPTION, CURRENT_TIMESTAMP());

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.STRUCTURAL_PROPOSAL_SNAPSHOT TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.COMMITTEE_HEARING TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.COMMITTEE_ROLE_OUTPUT TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.COMMITTEE_EVIDENCE_ARTIFACT TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.COMMITTEE_FINAL_DECISION TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON TABLE MIP.APP.STRUCTURAL_TRADE_PROPOSALS TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON TABLE MIP.APP.APP_CONFIG TO ROLE MIP_UI_API_ROLE;

-- Structural timeline price/state for evidence (if not already granted)
GRANT SELECT ON VIEW MIP.MART.V_STRUCTURAL_TIMELINE_PRICE TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON VIEW MIP.MART.V_STRUCTURAL_TIMELINE_SUMMARY TO ROLE MIP_UI_API_ROLE;

SELECT CONFIG_KEY, CONFIG_VALUE FROM MIP.APP.APP_CONFIG WHERE CONFIG_KEY = 'COMMITTEE2_ENABLED';
