-- Phase 5: stateful Brooks pattern instances (additive)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS REPLAY_ATTEMPT_ID VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS TRADING_DATE DATE;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS PATTERN_FAMILY VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS DIRECTION VARCHAR(16);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS CURRENT_TS TIMESTAMP_NTZ;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS SUPPORTING_OBSERVATION_IDS VARIANT;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS SUPPORTING_RULE_IDS VARIANT;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS RELEVANT_PRICES_JSON VARIANT;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS LIFECYCLE_HISTORY_JSON VARIANT;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS PATTERN_RULESET_VERSION VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS PARENT_PATTERN_INSTANCE_ID VARCHAR(36);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS CONFIRMATION_RULE_ID VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS FAILURE_RULE_ID VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS EXPIRY_RULE_ID VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS EXPLANATION VARCHAR(4000);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
    ADD COLUMN IF NOT EXISTS ACTION VARCHAR(32);

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_BAR_PATTERN_LINK (
    RUN_ID                 VARCHAR(36)   NOT NULL,
    REPLAY_ATTEMPT_ID      VARCHAR(64)   NOT NULL,
    SYMBOL                 VARCHAR(20)   NOT NULL,
    TRADING_DATE           DATE          NOT NULL,
    BAR_TS                 TIMESTAMP_NTZ NOT NULL,
    ACTIVE_PATTERN_IDS     VARIANT,
    PATTERN_SNAPSHOT_JSON  VARIANT,
    ACTION                 VARCHAR(32),
    EXPLANATION            VARCHAR(4000),
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RUN_ID, REPLAY_ATTEMPT_ID, SYMBOL, BAR_TS)
);

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_BAR_PATTERN_LINK TO ROLE MIP_UI_API_ROLE;
