-- Phase 4 strict geometry: stronger chair model + specialist token headroom.
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

MERGE INTO MIP.APP.APP_CONFIG t
USING (
    SELECT 'PHASE4_CHAIR_MODEL' AS CONFIG_KEY, 'mistral-large2' AS CONFIG_VALUE
    UNION ALL
    SELECT 'PHASE4_SPECIALIST_MAX_TOKENS', '2000'
) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN MATCHED THEN UPDATE SET CONFIG_VALUE = s.CONFIG_VALUE, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE) VALUES (s.CONFIG_KEY, s.CONFIG_VALUE);
