/* Brooks INTRADAY Adviser V1.0 — Cortex Search + literature enrichment for MIP_UI_API_ROLE */

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA MIP.KNOWLEDGE;

GRANT USAGE ON CORTEX SEARCH SERVICE MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_SEARCH_SERVICE TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON TABLE MIP.KNOWLEDGE.LITERATURE_RAG_DOCUMENT TO ROLE MIP_UI_API_ROLE;
