-- Phase 4 formal review baseline on replay attempts
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
    ADD COLUMN IF NOT EXISTS REVIEW_STATUS VARCHAR(32);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
    ADD COLUMN IF NOT EXISTS REVIEW_NOTES VARCHAR(1000);

UPDATE MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
SET REVIEW_STATUS = 'ARCHIVED_PHASE3_TRANSPORT',
    REVIEW_NOTES = 'Phase 3 placeholder transport not used for Brooks V0.1 review'
WHERE REPLAY_ATTEMPT_ID LIKE 'p3:%';

UPDATE MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
SET REVIEW_STATUS = COALESCE(REVIEW_STATUS, 'SUPERSEDED_INCOMPLETE'),
    REVIEW_NOTES = COALESCE(REVIEW_NOTES, 'Partial or abandoned Phase 4 run superseded for review')
WHERE RULESET_VERSION = 'BROOKS_OBJECTIVE_RULESET_V0_1'
  AND STATUS <> 'COMPLETED';
