/* Brooks INTRADAY Adviser V1.0 — MIP_UI_API_ROLE grants for New Validation launcher */

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_ADVISER_ATTEMPT TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_ADVISER_CALL TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_ADVISER_BAR TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_ADVISER_SIM_TRADE TO ROLE MIP_UI_API_ROLE;
