-- Brooks Intraday Lab Phase 4: immutable replay analysis attempts + observation versioning
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT (
    REPLAY_ATTEMPT_ID         VARCHAR(64)   NOT NULL PRIMARY KEY,
    RUN_ID                    VARCHAR(36)   NOT NULL,
    RULESET_VERSION           VARCHAR(64)   NOT NULL,
    STATUS                    VARCHAR(32)   NOT NULL,
    STARTING_CURSOR_JSON      VARIANT,
    OBSERVATION_COUNT         NUMBER,
    OBSERVATION_SEQUENCE_HASH VARCHAR(128),
    RULESET_PARAMETERS_JSON   VARIANT,
    NOTES                     VARCHAR(2000),
    CREATED_AT_UTC            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT_UTC            TIMESTAMP_NTZ
);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ADD COLUMN IF NOT EXISTS REPLAY_ATTEMPT_ID VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ADD COLUMN IF NOT EXISTS DERIVED_METRICS_JSON VARIANT;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ADD COLUMN IF NOT EXISTS RULE_EVALUATIONS_JSON VARIANT;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ADD COLUMN IF NOT EXISTS RULESET_VERSION VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ADD COLUMN IF NOT EXISTS VISIBLE_HISTORY_COUNT NUMBER;

UPDATE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
SET REPLAY_ATTEMPT_ID = 'p3:' || RUN_ID
WHERE REPLAY_ATTEMPT_ID IS NULL;

INSERT INTO MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT (
    REPLAY_ATTEMPT_ID, RUN_ID, RULESET_VERSION, STATUS, NOTES, OBSERVATION_COUNT
)
SELECT
    'p3:' || o.RUN_ID,
    o.RUN_ID,
    'BROOKS_REPLAY_TRANSPORT_V0_1',
    'COMPLETED',
    'Phase 3 placeholder transport observations (backfilled).',
    o.CNT
FROM (
    SELECT RUN_ID, COUNT(*) AS CNT
    FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    WHERE REPLAY_ATTEMPT_ID LIKE 'p3:%'
    GROUP BY RUN_ID
) o
WHERE NOT EXISTS (
    SELECT 1 FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT a
    WHERE a.REPLAY_ATTEMPT_ID = 'p3:' || o.RUN_ID
);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ALTER COLUMN REPLAY_ATTEMPT_ID SET NOT NULL;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    DROP PRIMARY KEY;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
    ADD PRIMARY KEY (RUN_ID, REPLAY_ATTEMPT_ID, SYMBOL, BAR_TS);

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT TO ROLE MIP_UI_API_ROLE;

UPDATE MIP.APP.BROOKS_INTRADAY_RUN
SET CONFIG_JSON = OBJECT_INSERT(
    OBJECT_INSERT(CONFIG_JSON, 'dossiers_frozen', TRUE, TRUE),
    'bars_frozen',
    TRUE,
    TRUE
)
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';
