-- Grants for Brooks Intraday Lab tables (UI API runtime)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_RUN TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT ON TABLE MIP.APP.BROOKS_INTRADAY_DOSSIER TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT ON TABLE MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_SIM_TRADE TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL TO ROLE MIP_UI_API_ROLE;

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT TO ROLE MIP_UI_API_ROLE;

GRANT SELECT ON TABLE MIP.APP.US_EQUITY_HOLIDAYS TO ROLE MIP_UI_API_ROLE;
