-- 20260415_structural_live_intent_schema.sql
-- Phase 2: Schema migration for structural proposal live-intent system.
-- Adds canonical structural fields to LIVE_ACTIONS, protection/trail fields
-- to LIVE_ORDERS, and trailing-stop feature flags to APP_CONFIG.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

------------------------------------------------------------------------
-- 1. LIVE_ACTIONS — Structural proposal identity
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS SETUP_EVENT_ID      NUMBER;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS MARKET_TYPE          VARCHAR(10);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS SETUP_FAMILY        VARCHAR(40);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS DIRECTION            VARCHAR(5);

------------------------------------------------------------------------
-- 2. LIVE_ACTIONS — Structural thesis
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS ENTRY_ZONE_LOW       NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS ENTRY_ZONE_HIGH      NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS SUPPORTING_LEVEL     NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS INVALIDATION_LEVEL   NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS INVALIDATION_RULE    VARCHAR(30);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS STRUCTURE_CONFIDENCE  NUMBER(9,6);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS LEVEL_SIGNIFICANCE   NUMBER(9,6);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS STRUCTURAL_STATE     VARCHAR(30);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS REGIME_TAGS          VARIANT;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS REGIME_COMPAT        VARCHAR(10);

------------------------------------------------------------------------
-- 3. LIVE_ACTIONS — Training / path evidence
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS TRUST_LABEL          VARCHAR(20);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS MEANINGFUL_HIT_RATE  NUMBER(9,6);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS PATH_SURVIVAL_RATE   NUMBER(9,6);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS MFE_MAE_RATIO        NUMBER(9,6);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS AVG_BARS_TO_THRESHOLD NUMBER;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS DOMINANT_FAILURE_MODE VARCHAR(40);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS BEST_WINDOW          NUMBER;

------------------------------------------------------------------------
-- 4. LIVE_ACTIONS — Intended trade management
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS RISK_CLASS           VARCHAR(20);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS EXIT_STYLE           VARCHAR(20);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS TRAIL_STYLE          VARCHAR(20);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS TRAIL_PARAMS         VARIANT;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATION_TYPE VARCHAR(30);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATION_PARAM NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS EXPECTED_HOLD_CHARACTER VARCHAR(20);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS MAX_HOLD_BARS        NUMBER;

------------------------------------------------------------------------
-- 5. LIVE_ACTIONS — Proposal narrative
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS SETUP_NARRATIVE      VARCHAR(500);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS PROPOSAL_RATIONALE   VARCHAR(500);

------------------------------------------------------------------------
-- 6. LIVE_ACTIONS — Freshness / current validation (populated at import)
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS LATEST_BAR_DATE      DATE;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS CURRENT_PRICE        NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS DISTANCE_TO_ENTRY_ZONE NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS SETUP_STILL_VALID    BOOLEAN;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS PRICE_MOVED_TOO_FAR  BOOLEAN;

ALTER TABLE MIP.LIVE.LIVE_ACTIONS
    ADD COLUMN IF NOT EXISTS FRESHNESS_ASSESSMENT VARCHAR(20);

------------------------------------------------------------------------
-- 7. LIVE_ORDERS — Parent/child protection linkage
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS PARENT_ORDER_ID      STRING;

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS ORDER_ROLE           STRING;

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS PROTECTION_TYPE      STRING;

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS OCA_GROUP            STRING;

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS STOP_PRICE           NUMBER(18,8);

------------------------------------------------------------------------
-- 8. LIVE_ORDERS — Trailing stop state
------------------------------------------------------------------------
ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_STYLE          VARCHAR(20);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATION_TYPE VARCHAR(30);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATION_PARAM NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_AMOUNT         NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_PERCENT        NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATION_PRICE NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATED      BOOLEAN DEFAULT FALSE;

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS TRAIL_ACTIVATED_AT   TIMESTAMP_NTZ;

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS LAST_KNOWN_STOP_LEVEL NUMBER(18,8);

ALTER TABLE MIP.LIVE.LIVE_ORDERS
    ADD COLUMN IF NOT EXISTS BROKER_TRAIL_STATE   VARCHAR(20);

------------------------------------------------------------------------
-- 9. APP_CONFIG — Trailing stop feature flags + long-only enforcement
------------------------------------------------------------------------
MERGE INTO MIP.APP.APP_CONFIG t
USING (
    SELECT 'TRAIL_ENABLED' AS CONFIG_KEY,
           'false'         AS CONFIG_VALUE,
           'Master switch for trailing stop order creation. Must be TRUE before any trailing orders are placed.' AS DESCRIPTION
    UNION ALL
    SELECT 'TRAIL_SHORT_ENABLED',
           'false',
           'Allow trailing stops on SHORT positions. Requires TRAIL_ENABLED=true. Gated behind short-side verification.'
    UNION ALL
    SELECT 'TRAIL_STYLES_ALLOWED',
           'STRUCTURAL',
           'Comma-separated list of allowed trail styles: STRUCTURAL, PROGRESS_BASED, HYBRID.'
    UNION ALL
    SELECT 'TRAIL_DRY_RUN',
           'true',
           'When true, trailing stop decisions are logged but no orders are placed at broker.'
    UNION ALL
    SELECT 'LIVE_ENFORCE_LONG_ONLY',
           'true',
           'When true, the live chain blocks SHORT entries. Set to false after short-side protection is verified.'
) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, UPDATED_AT)
VALUES (s.CONFIG_KEY, s.CONFIG_VALUE, s.DESCRIPTION, CURRENT_TIMESTAMP());

------------------------------------------------------------------------
-- 10. Verification queries
------------------------------------------------------------------------
SELECT 'LIVE_ACTIONS structural columns' AS CHECK_NAME,
       COUNT(*) AS COL_COUNT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'LIVE'
  AND TABLE_NAME = 'LIVE_ACTIONS'
  AND COLUMN_NAME IN (
      'SETUP_EVENT_ID', 'MARKET_TYPE', 'SETUP_FAMILY', 'DIRECTION',
      'ENTRY_ZONE_LOW', 'ENTRY_ZONE_HIGH', 'SUPPORTING_LEVEL',
      'INVALIDATION_LEVEL', 'INVALIDATION_RULE', 'STRUCTURE_CONFIDENCE',
      'LEVEL_SIGNIFICANCE', 'STRUCTURAL_STATE', 'REGIME_TAGS', 'REGIME_COMPAT',
      'TRUST_LABEL', 'MEANINGFUL_HIT_RATE', 'PATH_SURVIVAL_RATE',
      'MFE_MAE_RATIO', 'AVG_BARS_TO_THRESHOLD', 'DOMINANT_FAILURE_MODE', 'BEST_WINDOW',
      'RISK_CLASS', 'EXIT_STYLE', 'TRAIL_STYLE', 'TRAIL_PARAMS',
      'TRAIL_ACTIVATION_TYPE', 'TRAIL_ACTIVATION_PARAM',
      'EXPECTED_HOLD_CHARACTER', 'MAX_HOLD_BARS',
      'SETUP_NARRATIVE', 'PROPOSAL_RATIONALE',
      'LATEST_BAR_DATE', 'CURRENT_PRICE', 'DISTANCE_TO_ENTRY_ZONE',
      'SETUP_STILL_VALID', 'PRICE_MOVED_TOO_FAR', 'FRESHNESS_ASSESSMENT'
  );

SELECT 'LIVE_ORDERS protection/trail columns' AS CHECK_NAME,
       COUNT(*) AS COL_COUNT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'LIVE'
  AND TABLE_NAME = 'LIVE_ORDERS'
  AND COLUMN_NAME IN (
      'PARENT_ORDER_ID', 'ORDER_ROLE', 'PROTECTION_TYPE', 'OCA_GROUP', 'STOP_PRICE',
      'TRAIL_STYLE', 'TRAIL_ACTIVATION_TYPE', 'TRAIL_ACTIVATION_PARAM',
      'TRAIL_AMOUNT', 'TRAIL_PERCENT', 'TRAIL_ACTIVATION_PRICE',
      'TRAIL_ACTIVATED', 'TRAIL_ACTIVATED_AT', 'LAST_KNOWN_STOP_LEVEL', 'BROKER_TRAIL_STATE'
  );

SELECT 'APP_CONFIG trailing flags' AS CHECK_NAME,
       COUNT(*) AS FLAG_COUNT
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY IN ('TRAIL_ENABLED', 'TRAIL_SHORT_ENABLED', 'TRAIL_STYLES_ALLOWED', 'TRAIL_DRY_RUN', 'LIVE_ENFORCE_LONG_ONLY');
