/* Brooks Intraday Lab — dedicated 5-minute historical bar store (Phase 2B) */
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_HISTORICAL_BAR (
    SYMBOL                VARCHAR(20)   NOT NULL,
    BAR_TS_UTC            TIMESTAMP_NTZ NOT NULL,
    BAR_TS_NY             TIMESTAMP_NTZ NOT NULL,
    TRADING_DATE          DATE          NOT NULL,
    BAR_SIZE_MINUTES      NUMBER        NOT NULL,
    OPEN                  NUMBER(18, 6) NOT NULL,
    HIGH                  NUMBER(18, 6) NOT NULL,
    LOW                   NUMBER(18, 6) NOT NULL,
    CLOSE                 NUMBER(18, 6) NOT NULL,
    VOLUME                NUMBER(18, 2),
    RTH_FLAG              BOOLEAN       NOT NULL DEFAULT TRUE,
    SOURCE                VARCHAR(80)   NOT NULL,
    SOURCE_REQUEST_ID     VARCHAR(64),
    RETRIEVED_AT_UTC      TIMESTAMP_NTZ NOT NULL,
    DATA_QUALITY_STATUS   VARCHAR(32),
    SOURCE_METADATA_JSON  VARIANT,
    CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SYMBOL, BAR_TS_UTC, BAR_SIZE_MINUTES)
);

GRANT SELECT, INSERT ON TABLE MIP.APP.BROOKS_INTRADAY_HISTORICAL_BAR TO ROLE MIP_UI_API_ROLE;
