/* Brooks Phase 6/7 — MIP_UI_API_ROLE grants (API runtime uses this role, not MIP_ADMIN_ROLE) */
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION TO ROLE MIP_UI_API_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT TO ROLE MIP_UI_API_ROLE;
