-- Phase 6: context attempt and per-bar context observations

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT (
    CONTEXT_ATTEMPT_ID VARCHAR(36) NOT NULL,
    RUN_ID VARCHAR(36) NOT NULL,
    OBJECTIVE_ATTEMPT_ID VARCHAR(36) NOT NULL,
    PATTERN_ATTEMPT_ID VARCHAR(36) NOT NULL,
    CONTEXT_RULESET_VERSION VARCHAR(128) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    ROW_COUNT NUMBER,
    SEQUENCE_HASH VARCHAR(128),
    RULESET_PARAMETERS_JSON VARIANT,
    NOTES VARCHAR(4000),
    CREATED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT_UTC TIMESTAMP_NTZ,
    PRIMARY KEY (CONTEXT_ATTEMPT_ID)
);

CREATE TABLE IF NOT EXISTS MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION (
    CONTEXT_OBSERVATION_ID VARCHAR(36) NOT NULL,
    RUN_ID VARCHAR(36) NOT NULL,
    CONTEXT_ATTEMPT_ID VARCHAR(36) NOT NULL,
    SYMBOL VARCHAR(16) NOT NULL,
    TRADING_DATE DATE NOT NULL,
    BAR_TS TIMESTAMP_NTZ NOT NULL,
    SEQUENCE_NUM NUMBER NOT NULL,
    OBJECTIVE_ATTEMPT_ID VARCHAR(36) NOT NULL,
    PATTERN_ATTEMPT_ID VARCHAR(36) NOT NULL,
    DOSSIER_ID VARCHAR(128),
    CONTEXT_RULESET_VERSION VARCHAR(128) NOT NULL,
    THESIS_EFFECT VARCHAR(32) NOT NULL,
    STATE_BEFORE VARCHAR(64) NOT NULL,
    STATE_AFTER VARCHAR(64) NOT NULL,
    SELECTED_ACTION VARCHAR(64) NOT NULL,
    PAYLOAD_JSON VARIANT NOT NULL,
    EXPLANATION VARCHAR(4000),
    PRIMARY KEY (CONTEXT_OBSERVATION_ID),
    UNIQUE (CONTEXT_ATTEMPT_ID, SYMBOL, BAR_TS)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT TO ROLE MIP_ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION TO ROLE MIP_ADMIN_ROLE;
