-- Bump Phase 4 AI_COMPLETE statement timeout (PG/COST were hitting 120s cap).

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

UPDATE MIP.APP.APP_CONFIG
   SET CONFIG_VALUE = '240',
       UPDATED_AT = CURRENT_TIMESTAMP()
 WHERE CONFIG_KEY = 'PHASE4_COMPLETE_STATEMENT_TIMEOUT_SEC';

MERGE INTO MIP.APP.APP_CONFIG t
USING (
    SELECT 'PHASE4_COMPLETE_STATEMENT_TIMEOUT_SEC' AS CONFIG_KEY,
           '240' AS CONFIG_VALUE,
           'Statement timeout (seconds) per AI_COMPLETE call in Phase 4 board' AS DESCRIPTION
) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
    VALUES (s.CONFIG_KEY, s.CONFIG_VALUE, s.DESCRIPTION);
