-- Brooks Intraday Lab Phase 2 — additive dossier metadata columns
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_DOSSIER
    ADD COLUMN IF NOT EXISTS BOARD_RUN_ID VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_DOSSIER
    ADD COLUMN IF NOT EXISTS NORMALIZED_STATUS VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_DOSSIER
    ADD COLUMN IF NOT EXISTS COMPILER_VERSION VARCHAR(64);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_DOSSIER
    ADD COLUMN IF NOT EXISTS SOURCE_HASH VARCHAR(128);
