-- Revert Phase 4 chair to llama3.1-8b (mistral-large2 was too conservative — 0 PROPOSE).
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

MERGE INTO MIP.APP.APP_CONFIG t
USING (
    SELECT 'PHASE4_CHAIR_MODEL' AS CONFIG_KEY, 'llama3.1-8b' AS CONFIG_VALUE
) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN MATCHED THEN UPDATE SET CONFIG_VALUE = s.CONFIG_VALUE, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE) VALUES (s.CONFIG_KEY, s.CONFIG_VALUE);
