/* Phase C — additive SIMULATION_ATTEMPT_ID for trade/blocked isolation.
   No run-wide DELETE. Legacy blocked rows get LEGACY_UNSCOPED for PK eligibility. */
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_SIM_TRADE
  ADD COLUMN IF NOT EXISTS SIMULATION_ATTEMPT_ID VARCHAR(36);

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL
  ADD COLUMN IF NOT EXISTS SIMULATION_ATTEMPT_ID VARCHAR(36);

UPDATE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL
SET SIMULATION_ATTEMPT_ID = 'LEGACY_UNSCOPED'
WHERE SIMULATION_ATTEMPT_ID IS NULL;

ALTER TABLE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL DROP PRIMARY KEY;
ALTER TABLE MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL
  ADD PRIMARY KEY (RUN_ID, SIMULATION_ATTEMPT_ID, SYMBOL, SIGNAL_TS, CANDIDATE_ACTION);
