-- Phase 3 replay: allow reset (delete observations) via UI API role
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION TO ROLE MIP_UI_API_ROLE;
