-- v_intraday_ui_views.sql
-- Purpose: UI-facing views for FastAPI intraday training pages.

use role MIP_ADMIN_ROLE;
use database MIP;

create or replace view MIP.MART.V_INTRADAY_UI_SIGNALS as
select
    SIGNAL_ID,
    SIGNAL_NK_HASH,
    PATTERN_ID,
    MARKET_TYPE,
    SYMBOL,
    INTERVAL_MINUTES,
    SIGNAL_TS,
    SIGNAL_TS::date as SIGNAL_DATE,
    SIGNAL_SIDE,
    SCORE,
    STATE_BUCKET_ID,
    METRIC_VERSION,
    BUCKET_VERSION,
    GENERATED_AT
from MIP.APP.INTRA_SIGNALS
where INTERVAL_MINUTES = 15;

create or replace view MIP.MART.V_INTRADAY_UI_SIGNALS_DAILY as
select
    SIGNAL_DATE,
    PATTERN_ID,
    count(*) as SIGNALS_TOTAL,
    count(distinct SYMBOL) as SYMBOLS_COVERED
from MIP.MART.V_INTRADAY_UI_SIGNALS
group by 1,2;

create or replace view MIP.MART.V_INTRADAY_UI_TRUST as
select
    PATTERN_ID,
    MARKET_TYPE,
    INTERVAL_MINUTES,
    HORIZON_BARS,
    STATE_BUCKET_ID,
    N_SIGNALS,
    N_HITS,
    HIT_RATE,
    AVG_RETURN_NET,
    RETURN_STDDEV,
    CI_WIDTH,
    FALLBACK_LEVEL,
    FALLBACK_SOURCE_BUCKET_ID,
    METRIC_VERSION,
    BUCKET_VERSION,
    TRUST_VERSION,
    TRAIN_WINDOW_START,
    TRAIN_WINDOW_END,
    CALCULATED_AT,
    CALCULATED_AT::date as CALCULATED_DATE
from MIP.APP.INTRA_TRUST_STATS
where INTERVAL_MINUTES = 15;

create or replace view MIP.MART.V_INTRADAY_UI_TERRAIN as
select
    PATTERN_ID,
    MARKET_TYPE,
    SYMBOL,
    INTERVAL_MINUTES,
    TS,
    TS::date as TS_DATE,
    HORIZON_BARS,
    STATE_BUCKET_ID,
    EDGE,
    UNCERTAINTY,
    SUITABILITY,
    EDGE_Z,
    UNCERTAINTY_Z,
    SUITABILITY_Z,
    TERRAIN_SCORE,
    SHRINKAGE_K,
    WEIGHTS_JSON,
    N_SIGNALS,
    GLOBAL_BASELINE_RETURN,
    UPLIFT_RAW,
    SHRINKAGE_FACTOR,
    CANDIDATE_SOURCE,
    METRIC_VERSION,
    BUCKET_VERSION,
    TERRAIN_VERSION,
    CALCULATED_AT,
    CALCULATED_AT::date as CALCULATED_DATE
from MIP.APP.OPPORTUNITY_TERRAIN_15M
where INTERVAL_MINUTES = 15;

create or replace view MIP.MART.V_INTRADAY_UI_PATTERN_CATALOG as
select
    p.PATTERN_ID,
    p.NAME as PATTERN_NAME,
    p.PATTERN_TYPE,
    p.DESCRIPTION,
    p.PARAMS_JSON,
    p.ENABLED,
    p.IS_ACTIVE,
    coalesce(ip.IS_ENABLED, false) as INTRA_IS_ENABLED
from MIP.APP.PATTERN_DEFINITION p
left join MIP.APP.INTRA_PATTERN_DEFS ip
  on ip.PATTERN_ID = p.PATTERN_ID
where coalesce(p.PARAMS_JSON:interval_minutes::number, 1440) = 15;

create or replace view MIP.MART.V_INTRADAY_UI_BACKFILL_RUNS as
select
    RUN_ID,
    CHUNK_ID,
    START_TS,
    END_TS,
    STATUS,
    ROWS_STATE_SNAPSHOT,
    ROWS_STATE_TRANSITIONS,
    ROWS_SIGNALS,
    ROWS_OUTCOMES,
    ROWS_TRUST,
    ROWS_TERRAIN,
    ERROR_MESSAGE,
    DETAILS,
    CREATED_AT,
    UPDATED_AT
from MIP.APP.INTRA_BACKFILL_RUN_LOG;

