-- v_proposal_board_candidate_evidence.sql
-- Canonical deterministic evidence contract for the Agentic Proposal Board.
--
-- The board snapshot writer reads this view instead of querying raw evidence
-- tables ad hoc. It deliberately exposes board-visible warnings that the old
-- deterministic selector used to hide through filtering.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

CREATE OR REPLACE VIEW MIP.MART.V_PROPOSAL_BOARD_CANDIDATE_EVIDENCE AS
WITH cfg AS (
    SELECT
        COALESCE(MAX(IFF(CONFIG_KEY = 'PROPOSAL_BOARD_SHORT_RESEARCH_VISIBLE', TRY_TO_BOOLEAN(CONFIG_VALUE), NULL)), TRUE) AS SHORT_RESEARCH_VISIBLE,
        COALESCE(MAX(IFF(CONFIG_KEY = 'PROPOSAL_BOARD_SHORT_LIVE_ENABLED', TRY_TO_BOOLEAN(CONFIG_VALUE), NULL)), FALSE) AS SHORT_LIVE_ENABLED,
        COALESCE(MAX(IFF(CONFIG_KEY = 'PROPOSAL_BOARD_FX_LIVE_ENABLED', TRY_TO_BOOLEAN(CONFIG_VALUE), NULL)), FALSE) AS FX_LIVE_ENABLED
    FROM MIP.APP.APP_CONFIG
),
latest_daily AS (
    SELECT SYMBOL, MARKET_TYPE, TS AS LATEST_DAILY_TS, OPEN, HIGH, LOW, CLOSE
    FROM MIP.MART.MARKET_BARS
    WHERE INTERVAL_MINUTES = 1440
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SYMBOL, MARKET_TYPE
        ORDER BY TS DESC
    ) = 1
),
ingest_universe AS (
    SELECT
        UPPER(TRIM(SYMBOL)) AS SYMBOL_U,
        UPPER(TRIM(MARKET_TYPE)) AS MARKET_TYPE_U,
        MAX(IFF(COALESCE(IS_ENABLED, TRUE), 1, 0)) AS IS_ENABLED_NUM
    FROM MIP.APP.INGEST_UNIVERSE
    WHERE INTERVAL_MINUTES = 1440
    GROUP BY 1, 2
),
recent_actions AS (
    SELECT
        SYMBOL,
        MAX(IFF(STATUS IN ('REJECTED','CANCELLED','SUPERSEDED'), UPDATED_AT, NULL)) AS RECENT_TERMINAL_ACTION_TS,
        MAX(IFF(STATUS IN ('REJECTED','CANCELLED','SUPERSEDED')
                AND UPDATED_AT >= DATEADD('day', -14, CURRENT_TIMESTAMP()), 1, 0)) AS RECENT_TERMINAL_ACTION_14D,
        MAX(IFF(STATUS IN ('REJECTED','CANCELLED','SUPERSEDED')
                AND UPDATED_AT >= DATEADD('day', -14, CURRENT_TIMESTAMP()), STATUS, NULL)) AS RECENT_TERMINAL_ACTION_STATUS
    FROM MIP.LIVE.LIVE_ACTIONS
    WHERE LIVE_INTENT_KIND = 'STRUCTURAL'
    GROUP BY SYMBOL
),
recent_trade_intel AS (
    SELECT
        SYMBOL,
        MAX(EXIT_TS) AS RECENT_CLOSEOUT_TS,
        MAX(IFF(COALESCE(REALIZED_RETURN, 0) < 0, 1, 0)) AS RECENT_FAILED_TRADE_30D,
        MAX(OUTCOME_CLASS) AS RECENT_OUTCOME_CLASS
    FROM MIP.MART.V_TRADE_INTELLIGENCE
    WHERE EXIT_TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY SYMBOL
),
proposal_memory AS (
    SELECT
        SYMBOL,
        COUNT_IF(CREATED_AT >= DATEADD('day', -14, CURRENT_TIMESTAMP())) AS PROPOSALS_14D,
        MAX(CREATED_AT) AS LAST_PROPOSED_AT
    FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
    GROUP BY SYMBOL
),
opposing_setup AS (
    SELECT
        se.SETUP_EVENT_ID,
        MAX(IFF(opp.SETUP_EVENT_ID IS NOT NULL, 1, 0)) AS HAS_OPPOSING_SETUP,
        MAX(opp.SETUP_FAMILY) AS OPPOSING_SETUP_FAMILY,
        MAX(opp.STRUCTURE_CONFIDENCE) AS OPPOSING_STRUCTURE_CONFIDENCE
    FROM MIP.APP.STRUCTURAL_SETUP_EVENTS se
    LEFT JOIN MIP.APP.STRUCTURAL_SETUP_EVENTS opp
      ON opp.SYMBOL = se.SYMBOL
     AND opp.MARKET_TYPE = se.MARKET_TYPE
     AND opp.DIRECTION <> se.DIRECTION
     AND opp.SETUP_STATUS IN ('DETECTED', 'ELIGIBLE', 'WAITING', 'STALE')
     AND opp.SETUP_DATE >= DATEADD('day', -3, se.SETUP_DATE)
     AND COALESCE(opp.STRUCTURE_CONFIDENCE, 0) >= 0.65
    GROUP BY se.SETUP_EVENT_ID
)
SELECT
    se.SETUP_EVENT_ID,
    se.SETUP_EVENT_ID::VARCHAR AS SOURCE_CANDIDATE_KEY,
    se.SETUP_DATE,
    se.SYMBOL,
    se.MARKET_TYPE,
    se.DIRECTION,
    se.SETUP_FAMILY,
    se.STRUCTURAL_STATE,
    se.PRIOR_STATE,
    se.LEVEL_TYPE,
    se.LEVEL_PRICE,
    se.LEVEL_SIGNIFICANCE,
    se.ENTRY_ZONE_LOW,
    se.ENTRY_ZONE_HIGH,
    se.PRICE_INVALIDATION_LEVEL,
    se.INVALIDATION_RULE,
    se.INVALIDATION_BUFFER_ATR,
    COALESCE(rp.TRAIL_STYLE, se.TRAIL_STYLE) AS TRAIL_STYLE,
    COALESCE(rp.TRAIL_PARAMS, se.TRAIL_PARAMS) AS TRAIL_PARAMS,
    COALESCE(rp.EXIT_STYLE, tr.EXIT_STYLE_RECOMMENDATION, 'STRUCTURAL_TARGET') AS EXIT_STYLE,
    se.STRUCTURE_CONFIDENCE,
    se.WICK_CONFIRMATION_SCORE,
    se.THREE_BAR_CONFIRMATION_SCORE,
    se.TREND_CONTEXT_SCORE,
    se.REGIME_COMPAT,
    se.SETUP_STATUS,
    se.BARS_SINCE_DETECTION,
    se.DISTANCE_FROM_ENTRY_ZONE,
    se.ELIGIBLE_SINCE,
    se.EXPIRY_DATE,
    se.CONFLUENCE_FLAGS,
    se.VOLATILITY_CONTEXT,
    se.EXPECTED_MOVE_CLASS,
    CASE WHEN se.SETUP_FAMILY = 'BREAKOUT_RETEST_LONG' THEN 'GAP_AWARE' ELSE se.RISK_CLASS END AS RISK_CLASS,
    se.FEATURES_JSON,
    rg.VOL_REGIME,
    rg.TREND_REGIME,
    rg.RANGE_REGIME,
    rg.REGIME_SETUP_COMPAT,
    rg.ATR_20,
    rg.SMA_10_SLOPE,
    rg.SMA_20,
    rg.RANGE_10_HIGH,
    rg.RANGE_10_LOW,
    tr.N_SETUPS AS TRUST_SAMPLE_SIZE,
    tr.MEANINGFUL_HIT_RATE,
    tr.DIRECTIONAL_HIT_RATE,
    tr.PATH_SURVIVAL_HIT_RATE,
    tr.AVG_MFE,
    tr.AVG_MAE,
    tr.MFE_MAE_RATIO,
    tr.AVG_BARS_TO_THRESHOLD,
    tr.FAILURE_MODE_DISTRIBUTION,
    tr.BEST_WINDOW,
    COALESCE(tr.TRUST_LABEL, 'RESEARCH') AS TRUST_LABEL,
    tr.TRAIL_STRATEGY_RECOMMENDATION,
    tr.EXIT_STYLE_RECOMMENDATION,
    ps.PERCENTILE_25_MFE,
    ps.MEDIAN_MFE,
    ps.PERCENTILE_75_MFE,
    ps.PERCENTILE_25_MAE,
    ps.MEDIAN_MAE,
    ps.PCT_ADVERSE_BEFORE_FAVORABLE,
    ps.AVG_BARS_TO_MFE,
    ps.AVG_BARS_TO_MAE,
    ps.GAP_RISK_CONTRIBUTION,
    ld.LATEST_DAILY_TS,
    ld.OPEN AS LATEST_OPEN,
    ld.HIGH AS LATEST_HIGH,
    ld.LOW AS LATEST_LOW,
    ld.CLOSE AS LATEST_CLOSE,
    cfg.SHORT_RESEARCH_VISIBLE,
    cfg.SHORT_LIVE_ENABLED,
    cfg.FX_LIVE_ENABLED,
    COALESCE(iu.IS_ENABLED_NUM, 1) = 0 AS INSTRUMENT_DISABLED,
    (COALESCE(se.MARKET_TYPE, 'STOCK') = 'FX' AND NOT cfg.FX_LIVE_ENABLED) AS MARKET_TYPE_DISABLED_FOR_LIVE,
    (se.DIRECTION = 'SHORT' AND NOT cfg.SHORT_LIVE_ENABLED) AS DIRECTION_DISABLED_FOR_LIVE,
    FALSE AS LEGAL_TRADABILITY_EXCLUDED,
    COALESCE(os.HAS_OPPOSING_SETUP, 0) = 1 AS HAS_OPPOSING_SETUP,
    os.OPPOSING_SETUP_FAMILY,
    os.OPPOSING_STRUCTURE_CONFIDENCE,
    COALESCE(pm.PROPOSALS_14D, 0) AS PROPOSALS_14D,
    pm.LAST_PROPOSED_AT,
    COALESCE(ra.RECENT_TERMINAL_ACTION_14D, 0) = 1 AS RECENT_TERMINAL_ACTION_14D,
    ra.RECENT_TERMINAL_ACTION_TS,
    ra.RECENT_TERMINAL_ACTION_STATUS,
    COALESCE(rti.RECENT_FAILED_TRADE_30D, 0) = 1 AS RECENT_FAILED_TRADE_30D,
    rti.RECENT_CLOSEOUT_TS,
    rti.RECENT_OUTCOME_CLASS,
    (
        se.SYMBOL IS NULL
        OR se.SETUP_EVENT_ID IS NULL
        OR se.DIRECTION IS NULL
        OR se.ENTRY_ZONE_LOW IS NULL
        OR se.ENTRY_ZONE_HIGH IS NULL
        OR se.ENTRY_ZONE_HIGH < se.ENTRY_ZONE_LOW
        OR se.SETUP_STATUS IN ('INVALIDATED', 'EXPIRED')
        OR COALESCE(iu.IS_ENABLED_NUM, 1) = 0
        OR (COALESCE(se.MARKET_TYPE, 'STOCK') = 'FX' AND NOT cfg.FX_LIVE_ENABLED)
        OR FALSE
    ) AS ABSOLUTE_EXCLUDED,
    ARRAY_COMPACT(ARRAY_CONSTRUCT(
        IFF(se.SYMBOL IS NULL, 'MISSING_SYMBOL', NULL),
        IFF(se.SETUP_EVENT_ID IS NULL, 'MISSING_SETUP_EVENT_ID', NULL),
        IFF(se.DIRECTION IS NULL, 'MISSING_DIRECTION', NULL),
        IFF(se.ENTRY_ZONE_LOW IS NULL OR se.ENTRY_ZONE_HIGH IS NULL OR se.ENTRY_ZONE_HIGH < se.ENTRY_ZONE_LOW, 'ENTRY_ZONE_INVALID', NULL),
        IFF(se.SETUP_STATUS = 'INVALIDATED', 'SETUP_INVALIDATED', NULL),
        IFF(se.SETUP_STATUS = 'EXPIRED', 'SETUP_EXPIRED', NULL),
        IFF(COALESCE(iu.IS_ENABLED_NUM, 1) = 0, 'INSTRUMENT_DISABLED', NULL),
        IFF(COALESCE(se.MARKET_TYPE, 'STOCK') = 'FX' AND NOT cfg.FX_LIVE_ENABLED, 'MARKET_TYPE_DISABLED', NULL)
    )) AS ABSOLUTE_EXCLUSION_REASONS,
    ARRAY_COMPACT(ARRAY_CONSTRUCT(
        IFF(COALESCE(rti.RECENT_FAILED_TRADE_30D, 0) = 1, 'RECENT_FAILED_SYMBOL', NULL),
        IFF(COALESCE(pm.PROPOSALS_14D, 0) >= 2, 'REPEATED_REPITCH', NULL),
        IFF(COALESCE(os.HAS_OPPOSING_SETUP, 0) = 1, 'OPPOSING_SETUP', NULL),
        IFF(COALESCE(tr.TRUST_LABEL, 'RESEARCH') IN ('RESEARCH', 'REJECTED'), 'WEAK_TRUST_LABEL', NULL),
        IFF(se.SETUP_STATUS IN ('STALE', 'WAITING'), 'STALE_BUT_NOT_EXPIRED', NULL),
        IFF(ABS(COALESCE(se.DISTANCE_FROM_ENTRY_ZONE, 0)) > 2.0, 'PRICE_DISTANCE_FROM_ENTRY_ZONE', NULL),
        IFF(COALESCE(tr.N_SETUPS, 0) < 20, 'SPARSE_HISTORY', NULL),
        IFF(COALESCE(se.WICK_CONFIRMATION_SCORE, 1) < 0.25 AND COALESCE(se.THREE_BAR_CONFIRMATION_SCORE, 1) < 0.25, 'NOISY_CHOPPY_PRICE_ACTION', NULL),
        IFF(COALESCE(ra.RECENT_TERMINAL_ACTION_14D, 0) = 1, 'RECENT_TERMINAL_TRADE_OUTCOME', NULL),
        IFF(se.DIRECTION = 'SHORT' AND NOT cfg.SHORT_LIVE_ENABLED, 'DIRECTION_NOT_EXECUTABLE', NULL)
    )) AS BOARD_WARNING_FLAGS,
    OBJECT_CONSTRUCT_KEEP_NULL(
        'setup', OBJECT_CONSTRUCT_KEEP_NULL(
            'setup_event_id', se.SETUP_EVENT_ID,
            'setup_family', se.SETUP_FAMILY,
            'direction', se.DIRECTION,
            'symbol', se.SYMBOL,
            'market_type', se.MARKET_TYPE,
            'setup_date', se.SETUP_DATE,
            'setup_status', se.SETUP_STATUS
        ),
        'structure', OBJECT_CONSTRUCT_KEEP_NULL(
            'structural_state', se.STRUCTURAL_STATE,
            'prior_state', se.PRIOR_STATE,
            'level_type', se.LEVEL_TYPE,
            'level_price', se.LEVEL_PRICE,
            'level_significance', se.LEVEL_SIGNIFICANCE,
            'structure_confidence', se.STRUCTURE_CONFIDENCE,
            'wick_confirmation_score', se.WICK_CONFIRMATION_SCORE,
            'three_bar_confirmation_score', se.THREE_BAR_CONFIRMATION_SCORE,
            'trend_context_score', se.TREND_CONTEXT_SCORE
        ),
        'regime', OBJECT_CONSTRUCT_KEEP_NULL(
            'regime_compat', se.REGIME_COMPAT,
            'vol_regime', rg.VOL_REGIME,
            'trend_regime', rg.TREND_REGIME,
            'range_regime', rg.RANGE_REGIME,
            'atr_20', rg.ATR_20
        ),
        'execution', OBJECT_CONSTRUCT_KEEP_NULL(
            'entry_zone_low', se.ENTRY_ZONE_LOW,
            'entry_zone_high', se.ENTRY_ZONE_HIGH,
            'invalidation', se.PRICE_INVALIDATION_LEVEL,
            'invalidation_rule', se.INVALIDATION_RULE,
            'trail_style', COALESCE(rp.TRAIL_STYLE, se.TRAIL_STYLE),
            'trail_params', COALESCE(rp.TRAIL_PARAMS, se.TRAIL_PARAMS),
            'exit_style', COALESCE(rp.EXIT_STYLE, tr.EXIT_STYLE_RECOMMENDATION, 'STRUCTURAL_TARGET'),
            'risk_class', CASE WHEN se.SETUP_FAMILY = 'BREAKOUT_RETEST_LONG' THEN 'GAP_AWARE' ELSE se.RISK_CLASS END
        ),
        'history', OBJECT_CONSTRUCT_KEEP_NULL(
            'trust_label', COALESCE(tr.TRUST_LABEL, 'RESEARCH'),
            'trust_sample_size', tr.N_SETUPS,
            'meaningful_hit_rate', tr.MEANINGFUL_HIT_RATE,
            'path_survival_hit_rate', tr.PATH_SURVIVAL_HIT_RATE,
            'mfe_mae_ratio', tr.MFE_MAE_RATIO,
            'median_mfe', ps.MEDIAN_MFE,
            'median_mae', ps.MEDIAN_MAE,
            'gap_risk_contribution', ps.GAP_RISK_CONTRIBUTION
        ),
        'warnings', ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(COALESCE(rti.RECENT_FAILED_TRADE_30D, 0) = 1, 'RECENT_FAILED_SYMBOL', NULL),
            IFF(COALESCE(pm.PROPOSALS_14D, 0) >= 2, 'REPEATED_REPITCH', NULL),
            IFF(COALESCE(os.HAS_OPPOSING_SETUP, 0) = 1, 'OPPOSING_SETUP', NULL),
            IFF(COALESCE(tr.TRUST_LABEL, 'RESEARCH') IN ('RESEARCH', 'REJECTED'), 'WEAK_TRUST_LABEL', NULL),
            IFF(se.SETUP_STATUS IN ('STALE', 'WAITING'), 'STALE_BUT_NOT_EXPIRED', NULL),
            IFF(ABS(COALESCE(se.DISTANCE_FROM_ENTRY_ZONE, 0)) > 2.0, 'PRICE_DISTANCE_FROM_ENTRY_ZONE', NULL),
            IFF(COALESCE(tr.N_SETUPS, 0) < 20, 'SPARSE_HISTORY', NULL),
            IFF(COALESCE(se.WICK_CONFIRMATION_SCORE, 1) < 0.25 AND COALESCE(se.THREE_BAR_CONFIRMATION_SCORE, 1) < 0.25, 'NOISY_CHOPPY_PRICE_ACTION', NULL),
            IFF(COALESCE(ra.RECENT_TERMINAL_ACTION_14D, 0) = 1, 'RECENT_TERMINAL_TRADE_OUTCOME', NULL),
            IFF(se.DIRECTION = 'SHORT' AND NOT cfg.SHORT_LIVE_ENABLED, 'DIRECTION_NOT_EXECUTABLE', NULL)
        )),
        'absolute_exclusions', ARRAY_COMPACT(ARRAY_CONSTRUCT(
            IFF(se.SYMBOL IS NULL, 'MISSING_SYMBOL', NULL),
            IFF(se.SETUP_EVENT_ID IS NULL, 'MISSING_SETUP_EVENT_ID', NULL),
            IFF(se.DIRECTION IS NULL, 'MISSING_DIRECTION', NULL),
            IFF(se.ENTRY_ZONE_LOW IS NULL OR se.ENTRY_ZONE_HIGH IS NULL OR se.ENTRY_ZONE_HIGH < se.ENTRY_ZONE_LOW, 'ENTRY_ZONE_INVALID', NULL),
            IFF(se.SETUP_STATUS = 'INVALIDATED', 'SETUP_INVALIDATED', NULL),
            IFF(se.SETUP_STATUS = 'EXPIRED', 'SETUP_EXPIRED', NULL),
            IFF(COALESCE(iu.IS_ENABLED_NUM, 1) = 0, 'INSTRUMENT_DISABLED', NULL),
            IFF(COALESCE(se.MARKET_TYPE, 'STOCK') = 'FX' AND NOT cfg.FX_LIVE_ENABLED, 'MARKET_TYPE_DISABLED', NULL)
        ))
    ) AS EVIDENCE_PAYLOAD_JSON
FROM MIP.APP.STRUCTURAL_SETUP_EVENTS se
CROSS JOIN cfg
LEFT JOIN MIP.APP.STRUCTURAL_REGIME_TAG rg
  ON rg.SYMBOL = se.SYMBOL
 AND rg.MARKET_TYPE = se.MARKET_TYPE
 AND rg.AS_OF_DATE = se.SETUP_DATE
LEFT JOIN MIP.APP.STRUCTURAL_SETUP_TRUST tr
  ON tr.SETUP_FAMILY = se.SETUP_FAMILY
 AND tr.MARKET_TYPE = se.MARKET_TYPE
 AND tr.EVAL_WINDOW = 20
LEFT JOIN MIP.APP.STRUCTURAL_PATH_STATS ps
  ON ps.SETUP_FAMILY = se.SETUP_FAMILY
 AND ps.MARKET_TYPE = se.MARKET_TYPE
 AND ps.EVAL_WINDOW = 20
LEFT JOIN MIP.APP.STRUCTURAL_RISK_POLICY rp
  ON rp.SETUP_FAMILY = se.SETUP_FAMILY
 AND rp.DIRECTION = se.DIRECTION
 AND rp.IS_ACTIVE = TRUE
LEFT JOIN latest_daily ld
  ON ld.SYMBOL = se.SYMBOL
 AND ld.MARKET_TYPE = se.MARKET_TYPE
LEFT JOIN ingest_universe iu
  ON iu.SYMBOL_U = UPPER(TRIM(se.SYMBOL))
 AND iu.MARKET_TYPE_U = UPPER(TRIM(se.MARKET_TYPE))
LEFT JOIN recent_actions ra
  ON ra.SYMBOL = se.SYMBOL
LEFT JOIN recent_trade_intel rti
  ON rti.SYMBOL = se.SYMBOL
LEFT JOIN proposal_memory pm
  ON pm.SYMBOL = se.SYMBOL
LEFT JOIN opposing_setup os
  ON os.SETUP_EVENT_ID = se.SETUP_EVENT_ID
WHERE se.SETUP_STATUS IN ('DETECTED', 'ELIGIBLE', 'WAITING', 'STALE', 'INVALIDATED', 'EXPIRED')
  AND (se.DIRECTION <> 'SHORT' OR cfg.SHORT_RESEARCH_VISIBLE);
