-- 231_parallel_world_run_log.sql
-- Purpose: Run log for Parallel Worlds — one row per invocation of SP_RUN_PARALLEL_WORLDS.
-- Tracks status, timing, and summary stats for auditability.
-- RUN_ID is a UUID generated by the caller or the procedure.

use role MIP_ADMIN_ROLE;
use database MIP;

create table if not exists MIP.APP.PARALLEL_WORLD_RUN_LOG (
    RUN_ID          varchar(64)   not null,
    AS_OF_TS        timestamp_ntz not null,
    PORTFOLIO_ID    number,                        -- NULL for global (all-portfolio) runs
    SCENARIO_SET    varchar(64)   default 'DEFAULT_ACTIVE',
    STATUS          varchar(32)   default 'RUNNING',   -- RUNNING | COMPLETED | FAILED
    STARTED_AT      timestamp_ntz default current_timestamp(),
    COMPLETED_AT    timestamp_ntz,
    DETAILS         variant,                       -- JSON with scenario_count, result_count, errors, etc.

    constraint PK_PW_RUN_LOG primary key (RUN_ID)
);
