-- 233_parallel_world_recommendation.sql
-- Purpose: Stores ranked tuning recommendations generated by SP_GENERATE_PW_RECOMMENDATIONS.
-- Each row is a first-class recommendation object with confidence, safety checks,
-- evidence provenance, and governance status.
-- MERGE key on (PORTFOLIO_ID, SWEEP_FAMILY, RECOMMENDATION_TYPE, AS_OF_TS) ensures idempotency.

use role MIP_ADMIN_ROLE;
use database MIP;

create table if not exists MIP.APP.PARALLEL_WORLD_RECOMMENDATION (
    REC_ID                  number          autoincrement,
    RUN_ID                  varchar(64)     not null,
    PORTFOLIO_ID            number          not null,
    AS_OF_TS                timestamp_ntz   not null,
    RECOMMENDATION_TYPE     varchar(32)     not null,      -- CONSERVATIVE | AGGRESSIVE
    DOMAIN                  varchar(32)     not null,      -- SIGNAL | PORTFOLIO
    SWEEP_FAMILY            varchar(64)     not null,
    SCENARIO_ID             number          not null,
    PARAMETER_NAME          varchar(128),
    CURRENT_VALUE           varchar(64),
    RECOMMENDED_VALUE       varchar(64),
    EXPECTED_DAILY_DELTA    number(18,4),
    EXPECTED_CUMULATIVE_DELTA number(18,4),
    WIN_RATE_PCT            number(18,2),
    OBSERVATION_DAYS        number,
    CONFIDENCE_CLASS        varchar(32),                    -- STRONG | EMERGING | WEAK | NOISE
    CONFIDENCE_REASON       varchar(512),
    REGIME_FRAGILE          boolean         default false,
    REGIME_DETAIL           varchar(512),
    SAFETY_STATUS           varchar(32)     default 'NOT_READY',  -- READY_FOR_REVIEW | NOT_READY
    SAFETY_DETAIL           variant,                        -- JSON array of individual checks
    EVIDENCE_HASH           varchar(64),                    -- md5 of underlying surface data
    APPROVAL_STATUS         varchar(32)     default 'NOT_REVIEWED', -- NOT_REVIEWED | APPROVED | REJECTED | STALE
    ROLLBACK_NOTE           varchar(512),
    CREATED_AT              timestamp_ntz   default current_timestamp(),

    constraint PK_PW_RECOMMENDATION primary key (REC_ID)
);
