/*  ================================================================
    504_sp_detect_structural_setups.sql
    MIP Structural Strategy Framework — Setup Detection
    Phase 2e: State-gated detection of all 8 setup families with
    4-layer invalidation, evidence scoring, and conflict resolution.
    ================================================================ */

CREATE OR REPLACE PROCEDURE MIP.APP.SP_DETECT_STRUCTURAL_SETUPS(
    P_AS_OF_DATE   DATE     DEFAULT NULL,
    P_SYMBOL       VARCHAR  DEFAULT NULL
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_as_of       DATE     := COALESCE(P_AS_OF_DATE, CURRENT_DATE());
    v_run_start   TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    v_setups_ins  INTEGER  := 0;
    v_conflicts   INTEGER  := 0;
BEGIN

    -- ============================================================
    -- STEP 1: Build working set — current bar + recent bars + state + regime + levels
    -- ============================================================
    CREATE OR REPLACE TEMPORARY TABLE TMP_DET_BARS AS
    SELECT
        SYMBOL, MARKET_TYPE, TS, OPEN, HIGH, LOW, CLOSE,
        ROW_NUMBER() OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS DESC) AS RN_DESC,
        LAG(OPEN,1)  OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV1_OPEN,
        LAG(CLOSE,1) OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV1_CLOSE,
        LAG(HIGH,1)  OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV1_HIGH,
        LAG(LOW,1)   OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV1_LOW,
        LAG(OPEN,2)  OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV2_OPEN,
        LAG(CLOSE,2) OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV2_CLOSE,
        LAG(HIGH,2)  OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV2_HIGH,
        LAG(LOW,2)   OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY TS) AS PREV2_LOW
    FROM MIP.MART.MARKET_BARS
    WHERE INTERVAL_MINUTES = 1440
      AND TS <= :v_as_of
      AND (:P_SYMBOL IS NULL OR SYMBOL = :P_SYMBOL);

    CREATE OR REPLACE TEMPORARY TABLE TMP_DET_CONTEXT AS
    SELECT
        b.SYMBOL, b.MARKET_TYPE, b.TS,
        b.OPEN, b.HIGH, b.LOW, b.CLOSE,
        b.PREV1_OPEN, b.PREV1_CLOSE, b.PREV1_HIGH, b.PREV1_LOW,
        b.PREV2_OPEN, b.PREV2_CLOSE, b.PREV2_HIGH, b.PREV2_LOW,

        -- Bar metrics
        b.HIGH - b.LOW AS BAR_RANGE,
        CASE WHEN b.HIGH - b.LOW > 0 THEN (LEAST(b.OPEN, b.CLOSE) - b.LOW) / (b.HIGH - b.LOW) ELSE 0 END AS LOWER_WICK_RATIO,
        CASE WHEN b.HIGH - b.LOW > 0 THEN (b.HIGH - GREATEST(b.OPEN, b.CLOSE)) / (b.HIGH - b.LOW) ELSE 0 END AS UPPER_WICK_RATIO,
        CASE WHEN b.HIGH - b.LOW > 0 THEN (b.CLOSE - b.LOW) / (b.HIGH - b.LOW) ELSE 0.5 END AS CLOSE_LOCATION,

        -- State machine
        st.STRUCTURAL_STATE, st.PRIOR_STATE, st.STATE_CONFIDENCE,

        -- Regime
        rg.VOL_REGIME, rg.TREND_REGIME, rg.ATR_20,
        rg.REGIME_SETUP_COMPAT,

        -- Nearest support zone
        sz.LEVEL_PRICE  AS SUPPORT_PRICE,
        sz.LEVEL_LOW    AS SUPPORT_LOW,
        sz.LEVEL_HIGH   AS SUPPORT_HIGH,
        sz.LEVEL_SIGNIFICANCE AS SUPPORT_SIG,

        -- Nearest resistance zone
        rz.LEVEL_PRICE  AS RESISTANCE_PRICE,
        rz.LEVEL_LOW    AS RESISTANCE_LOW,
        rz.LEVEL_HIGH   AS RESISTANCE_HIGH,
        rz.LEVEL_SIGNIFICANCE AS RESISTANCE_SIG

    FROM TMP_DET_BARS b
    LEFT JOIN MIP.APP.STRUCTURAL_STATE_LOG st
      ON st.SYMBOL = b.SYMBOL AND st.MARKET_TYPE = b.MARKET_TYPE AND st.AS_OF_DATE = :v_as_of
    LEFT JOIN MIP.APP.STRUCTURAL_REGIME_TAG rg
      ON rg.SYMBOL = b.SYMBOL AND rg.MARKET_TYPE = b.MARKET_TYPE AND rg.AS_OF_DATE = :v_as_of
    LEFT JOIN (
        SELECT SYMBOL, MARKET_TYPE, LEVEL_PRICE, LEVEL_LOW, LEVEL_HIGH, LEVEL_SIGNIFICANCE,
            ROW_NUMBER() OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY LEVEL_SIGNIFICANCE DESC) AS RK
        FROM MIP.APP.STRUCTURAL_LEVEL_CACHE
        WHERE AS_OF_DATE = :v_as_of AND LEVEL_TYPE = 'SUPPORT_ZONE'
          AND (:P_SYMBOL IS NULL OR SYMBOL = :P_SYMBOL)
    ) sz ON sz.SYMBOL = b.SYMBOL AND sz.MARKET_TYPE = b.MARKET_TYPE AND sz.RK <= 3
    LEFT JOIN (
        SELECT SYMBOL, MARKET_TYPE, LEVEL_PRICE, LEVEL_LOW, LEVEL_HIGH, LEVEL_SIGNIFICANCE,
            ROW_NUMBER() OVER (PARTITION BY SYMBOL, MARKET_TYPE ORDER BY LEVEL_SIGNIFICANCE DESC) AS RK
        FROM MIP.APP.STRUCTURAL_LEVEL_CACHE
        WHERE AS_OF_DATE = :v_as_of AND LEVEL_TYPE = 'RESISTANCE_ZONE'
          AND (:P_SYMBOL IS NULL OR SYMBOL = :P_SYMBOL)
    ) rz ON rz.SYMBOL = b.SYMBOL AND rz.MARKET_TYPE = b.MARKET_TYPE AND rz.RK <= 3
    WHERE b.RN_DESC = 1;

    -- De-duplicate: keep only the closest support and resistance per symbol
    CREATE OR REPLACE TEMPORARY TABLE TMP_DET_FINAL AS
    SELECT * FROM (
        SELECT dc.*,
            ROW_NUMBER() OVER (
                PARTITION BY dc.SYMBOL, dc.MARKET_TYPE
                ORDER BY
                    ABS(dc.CLOSE - COALESCE(dc.SUPPORT_PRICE, 999999)) +
                    ABS(dc.CLOSE - COALESCE(dc.RESISTANCE_PRICE, 999999))
            ) AS PROXIMITY_RK
        FROM TMP_DET_CONTEXT dc
    )
    WHERE PROXIMITY_RK = 1;

    -- ============================================================
    -- STEP 2: Detect setups — each family gated by structural state
    -- ============================================================
    DELETE FROM MIP.APP.STRUCTURAL_SETUP_EVENTS
    WHERE SETUP_DATE = :v_as_of
      AND (:P_SYMBOL IS NULL OR SYMBOL = :P_SYMBOL);

    -- ----- A. BREAKOUT_RETEST_LONG -----
    -- Required state: PULLBACK_IN_TREND (after BREAKOUT_EXPANSION)
    -- OR: RANGE_BOUND / TREND_UP with close near a recently-broken resistance (now support)
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'BREAKOUT_RETEST_LONG', 'LONG', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'SUPPORT', d.RESISTANCE_PRICE, d.RESISTANCE_SIG,
        d.RESISTANCE_PRICE - 0.5 * d.ATR_20,
        d.RESISTANCE_PRICE + 0.5 * d.ATR_20,
        d.RESISTANCE_PRICE,  -- Layer 1: the breakout level itself
        'CONFIRMED_CLOSE_BEYOND', 0.3,
        'MFE >= 1x risk distance',
        d.RESISTANCE_PRICE + ABS(d.CLOSE - d.RESISTANCE_PRICE) + d.ATR_20,
        'STRUCTURAL',
        OBJECT_CONSTRUCT('type', 'structural_trailing'),
        -- STRUCTURE_CONFIDENCE
        LEAST(1.0,
            COALESCE(d.RESISTANCE_SIG, 0.3) * 0.5
          + CASE WHEN d.LOWER_WICK_RATIO >= 0.5 THEN 0.25 ELSE d.LOWER_WICK_RATIO * 0.5 END
          + CASE WHEN d.CLOSE_LOCATION >= 0.5 THEN 0.25 ELSE d.CLOSE_LOCATION * 0.5 END
        ),
        -- WICK_CONFIRMATION_SCORE
        LEAST(1.0, d.LOWER_WICK_RATIO / 0.5),
        -- THREE_BAR_CONFIRMATION_SCORE
        CASE
            WHEN d.PREV2_CLOSE < d.PREV2_OPEN AND d.CLOSE > d.OPEN AND d.CLOSE > d.PREV1_HIGH
            THEN 0.8 ELSE 0.0
        END,
        -- TREND_CONTEXT_SCORE
        CASE
            WHEN d.TREND_REGIME IN ('STRONG_TREND_UP','MODERATE_TREND_UP') THEN 0.9
            WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.5
            ELSE 0.2
        END,
        COALESCE(d.REGIME_SETUP_COMPAT:BREAKOUT_RETEST_LONG::VARCHAR, 'NEUTRAL'),
        'DETECTED',
        DATEADD('day', 7, :v_as_of),
        d.ATR_20,
        CASE WHEN ABS(d.CLOSE - d.RESISTANCE_PRICE) / NULLIF(d.ATR_20, 0) > 3 THEN 'HIGH'
             WHEN ABS(d.CLOSE - d.RESISTANCE_PRICE) / NULLIF(d.ATR_20, 0) > 1.5 THEN 'MEDIUM'
             ELSE 'LOW' END,
        OBJECT_CONSTRUCT('lower_wick_ratio', d.LOWER_WICK_RATIO, 'close_location', d.CLOSE_LOCATION,
                         'bar_range', d.BAR_RANGE, 'atr_20', d.ATR_20)
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('PULLBACK_IN_TREND', 'TREND_UP', 'RANGE_BOUND')
      AND d.RESISTANCE_PRICE IS NOT NULL
      AND d.RESISTANCE_SIG >= 0.30
      AND d.CLOSE >= d.RESISTANCE_LOW - 0.5 * d.ATR_20
      AND d.CLOSE <= d.RESISTANCE_HIGH + 1.0 * d.ATR_20
      AND (d.LOWER_WICK_RATIO >= 0.3 OR d.CLOSE_LOCATION >= 0.5);

    -- ----- B. SUPPORT_WICK_LONG -----
    -- Required state: RANGE_BOUND, PULLBACK_IN_TREND, or TREND_UP
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'SUPPORT_WICK_LONG', 'LONG', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'SUPPORT', d.SUPPORT_PRICE, d.SUPPORT_SIG,
        d.SUPPORT_PRICE,
        d.CLOSE,
        COALESCE(d.SUPPORT_LOW, d.SUPPORT_PRICE) - 0.0 * d.ATR_20,  -- Layer 1: zone boundary itself
        'SINGLE_CLOSE_BEYOND', 0.0,
        'MFE >= 1.5x ATR',
        d.CLOSE + 1.5 * d.ATR_20,
        'PROGRESS_BASED',
        OBJECT_CONSTRUCT('breakeven_at', 1.0, 'lock_50_at', 2.0, 'lock_60_at', 3.0),
        LEAST(1.0,
            COALESCE(d.SUPPORT_SIG, 0.3) * 0.4
          + d.LOWER_WICK_RATIO * 0.4
          + d.CLOSE_LOCATION * 0.2
        ),
        LEAST(1.0, d.LOWER_WICK_RATIO / 0.6),
        CASE WHEN d.PREV1_CLOSE < d.PREV1_OPEN AND d.PREV2_CLOSE < d.PREV2_OPEN THEN 0.6 ELSE 0.0 END,
        CASE
            WHEN d.TREND_REGIME IN ('STRONG_TREND_UP','MODERATE_TREND_UP') THEN 0.8
            WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.7
            ELSE 0.3
        END,
        COALESCE(d.REGIME_SETUP_COMPAT:SUPPORT_WICK_LONG::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        CASE WHEN ABS(d.CLOSE - d.SUPPORT_PRICE) / NULLIF(d.ATR_20, 0) > 3 THEN 'HIGH'
             WHEN ABS(d.CLOSE - d.SUPPORT_PRICE) / NULLIF(d.ATR_20, 0) > 1.5 THEN 'MEDIUM'
             ELSE 'LOW' END,
        OBJECT_CONSTRUCT('lower_wick_ratio', d.LOWER_WICK_RATIO, 'close_location', d.CLOSE_LOCATION,
                         'bar_range', d.BAR_RANGE, 'support_price', d.SUPPORT_PRICE)
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('RANGE_BOUND', 'PULLBACK_IN_TREND', 'TREND_UP')
      AND d.SUPPORT_PRICE IS NOT NULL
      AND d.SUPPORT_SIG >= 0.30
      AND d.LOW <= COALESCE(d.SUPPORT_HIGH, d.SUPPORT_PRICE + d.ATR_20)
      AND d.LOWER_WICK_RATIO >= 0.50
      AND d.CLOSE_LOCATION >= 0.45;

    -- ----- C. THREE_BAR_REVERSAL_LONG -----
    -- Required state: REVERSAL_FORMING, TREND_DOWN, PULLBACK_IN_TREND
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'THREE_BAR_REVERSAL_LONG', 'LONG', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'SUPPORT', COALESCE(d.SUPPORT_PRICE, d.LOW), COALESCE(d.SUPPORT_SIG, 0.3),
        d.CLOSE,
        d.HIGH,
        LEAST(d.LOW, COALESCE(d.PREV1_LOW, d.LOW), COALESCE(d.PREV2_LOW, d.LOW)),  -- 3-bar sequence low
        'SINGLE_CLOSE_BEYOND', 0.0,
        'Close above prior swing high',
        d.HIGH + d.ATR_20,
        'HYBRID',
        OBJECT_CONSTRUCT('initial', 'structural', 'switch_at_risk_multiple', 2.0),
        LEAST(1.0,
            0.5  -- base for 3-bar pattern
          + COALESCE(d.SUPPORT_SIG, 0.0) * 0.3
          + d.LOWER_WICK_RATIO * 0.2
        ),
        d.LOWER_WICK_RATIO,
        CASE
            WHEN d.PREV2_CLOSE < d.PREV2_OPEN AND d.CLOSE > d.OPEN AND d.CLOSE > COALESCE(d.PREV1_HIGH, d.CLOSE)
            THEN 0.9 ELSE 0.4
        END,
        CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_DOWN','MODERATE_TREND_DOWN') THEN 0.8
             WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.5
             ELSE 0.2 END,
        COALESCE(d.REGIME_SETUP_COMPAT:THREE_BAR_REVERSAL_LONG::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        'MEDIUM',
        OBJECT_CONSTRUCT('3bar_low', LEAST(d.LOW, COALESCE(d.PREV1_LOW, d.LOW), COALESCE(d.PREV2_LOW, d.LOW)),
                         'bar0_close_gt_bar1_high', d.CLOSE > COALESCE(d.PREV1_HIGH, d.CLOSE))
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('REVERSAL_FORMING', 'TREND_DOWN', 'PULLBACK_IN_TREND', 'RANGE_BOUND')
      AND d.PREV2_CLOSE < d.PREV2_OPEN   -- bar[-2] is down
      AND d.CLOSE > d.OPEN               -- bar[0] is up
      AND d.CLOSE > COALESCE(d.PREV1_HIGH, d.CLOSE - 1)  -- closes above bar[-1] high
      AND (d.SUPPORT_PRICE IS NULL
           OR d.LOW <= COALESCE(d.SUPPORT_HIGH, d.SUPPORT_PRICE) + 1.5 * d.ATR_20);

    -- ----- D. TREND_PULLBACK_LONG -----
    -- Required state: PULLBACK_IN_TREND (from TREND_UP), or TREND_UP with recent pullback
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'TREND_PULLBACK_LONG', 'LONG', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'SUPPORT', COALESCE(d.SUPPORT_PRICE, d.PREV1_LOW), COALESCE(d.SUPPORT_SIG, 0.3),
        d.CLOSE - 0.5 * d.ATR_20,
        d.CLOSE + 0.5 * d.ATR_20,
        COALESCE(d.SUPPORT_PRICE, d.PREV1_LOW) - 0.5 * d.ATR_20,
        'SINGLE_CLOSE_BEYOND', 0.0,
        'New high above pre-pullback swing high',
        d.HIGH + d.ATR_20,
        'STRUCTURAL',
        OBJECT_CONSTRUCT('type', 'structural_trailing'),
        LEAST(1.0,
            CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_UP','MODERATE_TREND_UP') THEN 0.5 ELSE 0.2 END
          + COALESCE(d.SUPPORT_SIG, 0.0) * 0.3
          + d.CLOSE_LOCATION * 0.2
        ),
        LEAST(1.0, d.LOWER_WICK_RATIO / 0.5),
        0.0,
        CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_UP') THEN 1.0
             WHEN d.TREND_REGIME = 'MODERATE_TREND_UP' THEN 0.8
             ELSE 0.3 END,
        COALESCE(d.REGIME_SETUP_COMPAT:TREND_PULLBACK_LONG::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        'LOW',
        OBJECT_CONSTRUCT('close_location', d.CLOSE_LOCATION, 'trend_regime', d.TREND_REGIME)
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('PULLBACK_IN_TREND', 'TREND_UP')
      AND d.TREND_REGIME IN ('STRONG_TREND_UP', 'MODERATE_TREND_UP')
      AND d.CLOSE > d.OPEN                 -- current bar is up (re-acceptance)
      AND d.CLOSE_LOCATION >= 0.45         -- closes in upper half
      AND d.PREV1_CLOSE < d.PREV1_OPEN;   -- prior bar was a down bar (pullback)

    -- ----- E. BREAKDOWN_RETEST_SHORT -----
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'BREAKDOWN_RETEST_SHORT', 'SHORT', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'RESISTANCE', d.SUPPORT_PRICE, d.SUPPORT_SIG,
        d.SUPPORT_PRICE - 0.5 * d.ATR_20,
        d.SUPPORT_PRICE + 0.5 * d.ATR_20,
        d.SUPPORT_PRICE,  -- Layer 1: the breakdown level
        'CONFIRMED_CLOSE_BEYOND', 0.3,
        'MFE >= 1x risk distance',
        d.SUPPORT_PRICE - ABS(d.CLOSE - d.SUPPORT_PRICE) - d.ATR_20,
        'PROGRESS_BASED',
        OBJECT_CONSTRUCT('breakeven_at', 1.0, 'lock_50_at', 2.0, 'lock_60_at', 3.0),
        LEAST(1.0,
            COALESCE(d.SUPPORT_SIG, 0.3) * 0.5
          + CASE WHEN d.UPPER_WICK_RATIO >= 0.5 THEN 0.25 ELSE d.UPPER_WICK_RATIO * 0.5 END
          + CASE WHEN d.CLOSE_LOCATION <= 0.5 THEN 0.25 ELSE (1.0 - d.CLOSE_LOCATION) * 0.5 END
        ),
        LEAST(1.0, d.UPPER_WICK_RATIO / 0.5),
        0.0,
        CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_DOWN','MODERATE_TREND_DOWN') THEN 0.9
             WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.5
             ELSE 0.2 END,
        COALESCE(d.REGIME_SETUP_COMPAT:BREAKDOWN_RETEST_SHORT::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        CASE WHEN ABS(d.CLOSE - d.SUPPORT_PRICE) / NULLIF(d.ATR_20, 0) > 3 THEN 'HIGH'
             WHEN ABS(d.CLOSE - d.SUPPORT_PRICE) / NULLIF(d.ATR_20, 0) > 1.5 THEN 'MEDIUM'
             ELSE 'LOW' END,
        OBJECT_CONSTRUCT('upper_wick_ratio', d.UPPER_WICK_RATIO, 'close_location', d.CLOSE_LOCATION)
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('PULLBACK_IN_TREND', 'TREND_DOWN', 'RANGE_BOUND')
      AND d.SUPPORT_PRICE IS NOT NULL
      AND d.SUPPORT_SIG >= 0.30
      AND d.CLOSE >= d.SUPPORT_LOW - 1.0 * d.ATR_20
      AND d.CLOSE <= d.SUPPORT_HIGH + 0.5 * d.ATR_20
      AND (d.UPPER_WICK_RATIO >= 0.3 OR d.CLOSE_LOCATION <= 0.5);

    -- ----- F. RESISTANCE_WICK_SHORT -----
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'RESISTANCE_WICK_SHORT', 'SHORT', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'RESISTANCE', d.RESISTANCE_PRICE, d.RESISTANCE_SIG,
        d.CLOSE,
        d.RESISTANCE_PRICE,
        COALESCE(d.RESISTANCE_HIGH, d.RESISTANCE_PRICE) + 0.0 * d.ATR_20,
        'SINGLE_CLOSE_BEYOND', 0.0,
        'MFE >= 1.5x ATR',
        d.CLOSE - 1.5 * d.ATR_20,
        'PROGRESS_BASED',
        OBJECT_CONSTRUCT('breakeven_at', 1.0, 'lock_50_at', 2.0, 'lock_60_at', 3.0),
        LEAST(1.0,
            COALESCE(d.RESISTANCE_SIG, 0.3) * 0.4
          + d.UPPER_WICK_RATIO * 0.4
          + (1.0 - d.CLOSE_LOCATION) * 0.2
        ),
        LEAST(1.0, d.UPPER_WICK_RATIO / 0.6),
        CASE WHEN d.PREV1_CLOSE > d.PREV1_OPEN AND d.PREV2_CLOSE > d.PREV2_OPEN THEN 0.6 ELSE 0.0 END,
        CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_DOWN','MODERATE_TREND_DOWN') THEN 0.8
             WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.7
             ELSE 0.3 END,
        COALESCE(d.REGIME_SETUP_COMPAT:RESISTANCE_WICK_SHORT::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        'MEDIUM',
        OBJECT_CONSTRUCT('upper_wick_ratio', d.UPPER_WICK_RATIO, 'close_location', d.CLOSE_LOCATION)
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('RANGE_BOUND', 'PULLBACK_IN_TREND', 'TREND_DOWN')
      AND d.RESISTANCE_PRICE IS NOT NULL
      AND d.RESISTANCE_SIG >= 0.30
      AND d.HIGH >= COALESCE(d.RESISTANCE_LOW, d.RESISTANCE_PRICE - d.ATR_20)
      AND d.UPPER_WICK_RATIO >= 0.50
      AND d.CLOSE_LOCATION <= 0.55;

    -- ----- G. THREE_BAR_REVERSAL_SHORT -----
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'THREE_BAR_REVERSAL_SHORT', 'SHORT', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'RESISTANCE', COALESCE(d.RESISTANCE_PRICE, d.HIGH), COALESCE(d.RESISTANCE_SIG, 0.3),
        d.LOW,
        d.CLOSE,
        GREATEST(d.HIGH, COALESCE(d.PREV1_HIGH, d.HIGH), COALESCE(d.PREV2_HIGH, d.HIGH)),
        'SINGLE_CLOSE_BEYOND', 0.0,
        'Close below prior swing low',
        d.LOW - d.ATR_20,
        'HYBRID',
        OBJECT_CONSTRUCT('initial', 'structural', 'switch_at_risk_multiple', 1.5),
        LEAST(1.0,
            0.5
          + COALESCE(d.RESISTANCE_SIG, 0.0) * 0.3
          + d.UPPER_WICK_RATIO * 0.2
        ),
        d.UPPER_WICK_RATIO,
        CASE
            WHEN d.PREV2_CLOSE > d.PREV2_OPEN AND d.CLOSE < d.OPEN AND d.CLOSE < COALESCE(d.PREV1_LOW, d.CLOSE)
            THEN 0.9 ELSE 0.4
        END,
        CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_UP','MODERATE_TREND_UP') THEN 0.8
             WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.5
             ELSE 0.2 END,
        COALESCE(d.REGIME_SETUP_COMPAT:THREE_BAR_REVERSAL_SHORT::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        'MEDIUM',
        OBJECT_CONSTRUCT('3bar_high', GREATEST(d.HIGH, COALESCE(d.PREV1_HIGH, d.HIGH), COALESCE(d.PREV2_HIGH, d.HIGH)))
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('REVERSAL_FORMING', 'TREND_UP', 'PULLBACK_IN_TREND', 'RANGE_BOUND')
      AND d.PREV2_CLOSE > d.PREV2_OPEN   -- bar[-2] is up
      AND d.CLOSE < d.OPEN               -- bar[0] is down
      AND d.CLOSE < COALESCE(d.PREV1_LOW, d.CLOSE + 1);

    -- ----- H. FAILED_BREAKOUT_SHORT -----
    INSERT INTO MIP.APP.STRUCTURAL_SETUP_EVENTS (
        SETUP_FAMILY, DIRECTION, SYMBOL, MARKET_TYPE, SETUP_DATE,
        STRUCTURAL_STATE, PRIOR_STATE, LEVEL_TYPE, LEVEL_PRICE, LEVEL_SIGNIFICANCE,
        ENTRY_ZONE_LOW, ENTRY_ZONE_HIGH,
        PRICE_INVALIDATION_LEVEL, INVALIDATION_RULE, INVALIDATION_BUFFER_ATR,
        TRAIL_ACTIVATION_CONDITION, TRAIL_ACTIVATION_THRESHOLD, TRAIL_STYLE, TRAIL_PARAMS,
        STRUCTURE_CONFIDENCE, WICK_CONFIRMATION_SCORE, THREE_BAR_CONFIRMATION_SCORE,
        TREND_CONTEXT_SCORE, REGIME_COMPAT,
        SETUP_STATUS, EXPIRY_DATE, VOLATILITY_CONTEXT, RISK_CLASS, FEATURES_JSON
    )
    SELECT
        'FAILED_BREAKOUT_SHORT', 'SHORT', d.SYMBOL, d.MARKET_TYPE, :v_as_of,
        d.STRUCTURAL_STATE, d.PRIOR_STATE,
        'FAILED_RECLAIM', COALESCE(d.RESISTANCE_PRICE, d.HIGH), COALESCE(d.RESISTANCE_SIG, 0.3),
        d.CLOSE - 0.5 * d.ATR_20,
        d.CLOSE,
        GREATEST(d.HIGH, COALESCE(d.PREV1_HIGH, d.HIGH)),  -- the failed breakout high
        'SINGLE_CLOSE_BEYOND', 0.0,
        'Immediate: close below pre-breakout range',
        COALESCE(d.SUPPORT_PRICE, d.LOW) - 0.5 * d.ATR_20,
        'STRUCTURAL',
        OBJECT_CONSTRUCT('type', 'fast_escalation', 'lock_at_risk_multiple', 1.5, 'lock_ratio', 0.6),
        LEAST(1.0,
            0.4
          + COALESCE(d.RESISTANCE_SIG, 0.0) * 0.3
          + d.UPPER_WICK_RATIO * 0.3
        ),
        LEAST(1.0, d.UPPER_WICK_RATIO / 0.4),
        0.0,
        CASE WHEN d.TREND_REGIME IN ('STRONG_TREND_DOWN','MODERATE_TREND_DOWN') THEN 0.8
             WHEN d.TREND_REGIME = 'NEUTRAL' THEN 0.6
             ELSE 0.3 END,
        COALESCE(d.REGIME_SETUP_COMPAT:FAILED_BREAKOUT_SHORT::VARCHAR, 'NEUTRAL'),
        'DETECTED', DATEADD('day', 7, :v_as_of), d.ATR_20,
        'MEDIUM',
        OBJECT_CONSTRUCT('upper_wick_ratio', d.UPPER_WICK_RATIO, 'failed_high', GREATEST(d.HIGH, COALESCE(d.PREV1_HIGH, d.HIGH)))
    FROM TMP_DET_FINAL d
    WHERE d.STRUCTURAL_STATE IN ('FAILED_MOVE', 'RANGE_BOUND', 'REVERSAL_FORMING',
                                  'TREND_UP', 'BREAKOUT_EXPANSION', 'PULLBACK_IN_TREND')
      AND d.RESISTANCE_PRICE IS NOT NULL
      AND d.RESISTANCE_SIG >= 0.20
      -- A recent bar attempted breakout (wick or close above resistance)
      AND (d.HIGH > COALESCE(d.RESISTANCE_HIGH, d.RESISTANCE_PRICE)
           OR COALESCE(d.PREV1_HIGH, 0) > COALESCE(d.RESISTANCE_HIGH, d.RESISTANCE_PRICE))
      -- Current bar closed back below resistance
      AND d.CLOSE < d.RESISTANCE_PRICE
      AND d.UPPER_WICK_RATIO >= 0.25;

    -- ============================================================
    -- STEP 3: Count inserted setups
    -- ============================================================
    SELECT COUNT(*) INTO :v_setups_ins
    FROM MIP.APP.STRUCTURAL_SETUP_EVENTS
    WHERE SETUP_DATE = :v_as_of
      AND (:P_SYMBOL IS NULL OR SYMBOL = :P_SYMBOL);

    -- ============================================================
    -- STEP 4: Conflict resolution
    -- ============================================================
    -- Opposing direction conflicts on same symbol
    INSERT INTO MIP.APP.STRUCTURAL_CONFLICT_LOG (
        SYMBOL, CONFLICT_DATE, SETUP_EVENT_ID_A, SETUP_EVENT_ID_B,
        CONFLICT_TYPE, RESOLUTION, RESOLUTION_REASON
    )
    WITH opposing AS (
        SELECT
            a.SYMBOL, a.SETUP_EVENT_ID AS ID_A, b.SETUP_EVENT_ID AS ID_B,
            a.STRUCTURE_CONFIDENCE * COALESCE(a.LEVEL_SIGNIFICANCE, 0.5) AS SCORE_A,
            b.STRUCTURE_CONFIDENCE * COALESCE(b.LEVEL_SIGNIFICANCE, 0.5) AS SCORE_B
        FROM MIP.APP.STRUCTURAL_SETUP_EVENTS a
        JOIN MIP.APP.STRUCTURAL_SETUP_EVENTS b
          ON b.SYMBOL = a.SYMBOL AND b.MARKET_TYPE = a.MARKET_TYPE
         AND b.SETUP_DATE = a.SETUP_DATE
         AND b.DIRECTION != a.DIRECTION
         AND b.SETUP_EVENT_ID > a.SETUP_EVENT_ID
        WHERE a.SETUP_DATE = :v_as_of
          AND a.SETUP_STATUS = 'DETECTED'
          AND b.SETUP_STATUS = 'DETECTED'
    )
    SELECT
        SYMBOL, :v_as_of, ID_A, ID_B, 'OPPOSING_DIRECTION',
        CASE
            WHEN SCORE_A >= 2.0 * SCORE_B THEN 'A_WINS'
            WHEN SCORE_B >= 2.0 * SCORE_A THEN 'B_WINS'
            ELSE 'BOTH_CANCELLED'
        END,
        CASE
            WHEN SCORE_A >= 2.0 * SCORE_B THEN 'A score ' || ROUND(SCORE_A, 3) || ' >= 2x B score ' || ROUND(SCORE_B, 3)
            WHEN SCORE_B >= 2.0 * SCORE_A THEN 'B score ' || ROUND(SCORE_B, 3) || ' >= 2x A score ' || ROUND(SCORE_A, 3)
            ELSE 'Ambiguous: A=' || ROUND(SCORE_A, 3) || ' B=' || ROUND(SCORE_B, 3)
        END
    FROM opposing;

    -- Apply conflict resolutions: cancel losing setups
    UPDATE MIP.APP.STRUCTURAL_SETUP_EVENTS
    SET SETUP_STATUS = 'INVALIDATED', STATUS_UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE SETUP_EVENT_ID IN (
        SELECT SETUP_EVENT_ID_B FROM MIP.APP.STRUCTURAL_CONFLICT_LOG
        WHERE CONFLICT_DATE = :v_as_of AND RESOLUTION = 'A_WINS'
        UNION ALL
        SELECT SETUP_EVENT_ID_A FROM MIP.APP.STRUCTURAL_CONFLICT_LOG
        WHERE CONFLICT_DATE = :v_as_of AND RESOLUTION = 'B_WINS'
        UNION ALL
        SELECT SETUP_EVENT_ID_A FROM MIP.APP.STRUCTURAL_CONFLICT_LOG
        WHERE CONFLICT_DATE = :v_as_of AND RESOLUTION = 'BOTH_CANCELLED'
        UNION ALL
        SELECT SETUP_EVENT_ID_B FROM MIP.APP.STRUCTURAL_CONFLICT_LOG
        WHERE CONFLICT_DATE = :v_as_of AND RESOLUTION = 'BOTH_CANCELLED'
    );

    -- Same-direction competing: keep highest score, mark others
    INSERT INTO MIP.APP.STRUCTURAL_CONFLICT_LOG (
        SYMBOL, CONFLICT_DATE, SETUP_EVENT_ID_A, SETUP_EVENT_ID_B,
        CONFLICT_TYPE, RESOLUTION, RESOLUTION_REASON
    )
    WITH ranked AS (
        SELECT SYMBOL, MARKET_TYPE, DIRECTION, SETUP_EVENT_ID,
            STRUCTURE_CONFIDENCE * COALESCE(LEVEL_SIGNIFICANCE, 0.5) AS SCORE,
            ROW_NUMBER() OVER (PARTITION BY SYMBOL, MARKET_TYPE, DIRECTION ORDER BY
                STRUCTURE_CONFIDENCE * COALESCE(LEVEL_SIGNIFICANCE, 0.5) DESC) AS RK
        FROM MIP.APP.STRUCTURAL_SETUP_EVENTS
        WHERE SETUP_DATE = :v_as_of AND SETUP_STATUS = 'DETECTED'
    ),
    same_dir AS (
        SELECT a.SYMBOL, a.SETUP_EVENT_ID AS ID_A, b.SETUP_EVENT_ID AS ID_B,
            a.SCORE AS SCORE_A, b.SCORE AS SCORE_B
        FROM ranked a
        JOIN ranked b
          ON b.SYMBOL = a.SYMBOL AND b.MARKET_TYPE = a.MARKET_TYPE
         AND b.DIRECTION = a.DIRECTION AND b.RK > a.RK
        WHERE a.RK = 1
    )
    SELECT SYMBOL, :v_as_of, ID_A, ID_B, 'SAME_DIRECTION_COMPETING',
        'A_WINS',
        'Primary thesis: A score ' || ROUND(SCORE_A, 3) || ' > B score ' || ROUND(SCORE_B, 3)
    FROM same_dir;

    -- Mark losing same-direction setups as EXPIRED (not the primary thesis)
    UPDATE MIP.APP.STRUCTURAL_SETUP_EVENTS
    SET SETUP_STATUS = 'EXPIRED', STATUS_UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE SETUP_EVENT_ID IN (
        SELECT SETUP_EVENT_ID_B FROM MIP.APP.STRUCTURAL_CONFLICT_LOG
        WHERE CONFLICT_DATE = :v_as_of AND CONFLICT_TYPE = 'SAME_DIRECTION_COMPETING'
    )
    AND SETUP_STATUS = 'DETECTED';

    SELECT COUNT(*) INTO :v_conflicts
    FROM MIP.APP.STRUCTURAL_CONFLICT_LOG WHERE CONFLICT_DATE = :v_as_of;

    -- Clean up
    DROP TABLE IF EXISTS TMP_DET_BARS;
    DROP TABLE IF EXISTS TMP_DET_CONTEXT;
    DROP TABLE IF EXISTS TMP_DET_FINAL;

    RETURN OBJECT_CONSTRUCT(
        'status',          'SUCCESS',
        'as_of_date',      :v_as_of,
        'setups_detected', :v_setups_ins,
        'conflicts',       :v_conflicts,
        'elapsed_sec',     DATEDIFF('second', :v_run_start, CURRENT_TIMESTAMP())
    );
END;
$$;
