-- grants_early_exit.sql
-- Purpose: Grant SELECT on early-exit and decision console objects to MIP_UI_API_ROLE.

use role MIP_ADMIN_ROLE;

GRANT SELECT ON MIP.APP.EARLY_EXIT_LOG TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.APP.EARLY_EXIT_POSITION_STATE TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.APP.APP_CONFIG TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.MART.V_EARLY_EXIT_OVERVIEW TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.MART.V_EARLY_EXIT_BY_SYMBOL TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.MART.V_EARLY_EXIT_HIT_DISTRIBUTION TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.MART.V_EARLY_EXIT_DETAIL TO ROLE MIP_UI_API_ROLE;
GRANT SELECT ON MIP.MART.V_EARLY_EXIT_POSITION_TRACKER TO ROLE MIP_UI_API_ROLE;
