use role MIP_ADMIN_ROLE;
use database MIP;

select 'LIVE_ACTIONS_REVALIDATION_OUTCOME_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'REVALIDATION_OUTCOME';

select 'LIVE_ACTIONS_REVALIDATION_POLICY_VERSION_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'REVALIDATION_POLICY_VERSION';

select 'LIVE_ACTIONS_REVALIDATION_DATA_SOURCE_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'REVALIDATION_DATA_SOURCE';

