use role MIP_ADMIN_ROLE;
use database MIP;

select 'LIVE_ACTIONS_INTENT_SUBMITTED_BY_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'INTENT_SUBMITTED_BY';

select 'LIVE_ACTIONS_INTENT_SUBMITTED_TS_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'INTENT_SUBMITTED_TS';

select 'LIVE_ACTIONS_INTENT_APPROVED_BY_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'INTENT_APPROVED_BY';

select 'LIVE_ACTIONS_INTENT_APPROVED_TS_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'INTENT_APPROVED_TS';

select 'LIVE_ACTIONS_INTENT_REFERENCE_ID_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'INTENT_REFERENCE_ID';

