/* ================================================================
   15_position_health_smoke.sql
   Daily Position Health V1 - smoke tests.

   Validates:
     1) DDL is in place (tables, agent, views, procedures)
     2) Feature flag and tunable APP_CONFIG entries exist
     3) SP_RUN_DAILY_POSITION_VERDICT runs cleanly for today
     4) DAILY_POSITION_VERDICT row counts and vocabulary
     5) POSITION_EPISODE_KEY is a hash and stable across reruns
     6) SP_UPDATE_SHADOW_POSITION_LIFECYCLE runs cleanly
     7) Comparison view returns rows with AGREEMENT_LABEL populated

   Read-only and idempotent. Re-runs SP_RUN_DAILY_POSITION_VERDICT to
   confirm idempotency by row count. Does NOT call the Cortex agent.
   ================================================================ */

USE ROLE MIP_ADMIN_ROLE;
USE WAREHOUSE MIP_WH_XS;
USE DATABASE MIP;
USE SCHEMA APP;

-- 1. DDL presence: tables.
SELECT 'TABLES_PRESENT' AS CHECK_NAME, COUNT(*) AS N
  FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA = 'APP'
   AND TABLE_NAME IN (
        'DAILY_POSITION_VERDICT',
        'DAILY_POSITION_SHADOW_REVIEW',
        'SHADOW_POSITION_LIFECYCLE'
   );
-- Expect 3.

-- 2. DDL presence: procedures.
SELECT 'PROCS_PRESENT' AS CHECK_NAME, COUNT(*) AS N
  FROM INFORMATION_SCHEMA.PROCEDURES
 WHERE PROCEDURE_SCHEMA = 'APP'
   AND PROCEDURE_NAME IN (
        'SP_RUN_DAILY_POSITION_VERDICT',
        'SP_UPDATE_SHADOW_POSITION_LIFECYCLE'
   );
-- Expect 2.

-- 3. DDL presence: mart views.
SELECT 'VIEWS_PRESENT' AS CHECK_NAME, COUNT(*) AS N
  FROM INFORMATION_SCHEMA.VIEWS
 WHERE TABLE_SCHEMA = 'MART'
   AND TABLE_NAME IN (
        'V_DAILY_POSITION_VERDICT_LATEST',
        'V_DAILY_POSITION_VERDICT_HISTORY',
        'V_DAILY_POSITION_SHADOW_REVIEW_LATEST',
        'V_DAILY_POSITION_SHADOW_REVIEW_HISTORY',
        'V_SHADOW_POSITION_LIFECYCLE_STATUS',
        'V_POSITION_HEALTH_COMPARISON_LATEST'
   );
-- Expect 6.

-- 4. APP_CONFIG entries.
SELECT 'APP_CONFIG_KEYS' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.APP_CONFIG
 WHERE CONFIG_KEY IN (
        'POSITION_HEALTH_ENABLED',
        'POSITION_HEALTH_SHADOW_ENABLED',
        'POSITION_HEALTH_DEFAULT_HORIZON_DAYS',
        'POSITION_HEALTH_PATH_LOOKBACK_DAYS',
        'POSITION_HEALTH_AGENT_NAME'
   );
-- Expect 5.

-- 5. Real engine smoke run for today.
CALL MIP.APP.SP_RUN_DAILY_POSITION_VERDICT(CURRENT_DATE());

-- 6. Verdict row count for today (after run).
SELECT 'VERDICT_ROWS_TODAY' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.DAILY_POSITION_VERDICT
 WHERE AS_OF_DATE = CURRENT_DATE();

-- 7. Vocabulary check: every VERDICT in the canonical set.
SELECT 'BAD_VERDICT' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.DAILY_POSITION_VERDICT
 WHERE AS_OF_DATE = CURRENT_DATE()
   AND VERDICT NOT IN ('KEEP', 'WATCH', 'EXIT_REVIEW');
-- Expect 0.

-- 8. Vocabulary check: every HEALTH_STATE in the canonical set.
SELECT 'BAD_HEALTH_STATE' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.DAILY_POSITION_VERDICT
 WHERE AS_OF_DATE = CURRENT_DATE()
   AND HEALTH_STATE NOT IN ('STRENGTHENING', 'INTACT', 'SLOW', 'DRIFTING', 'BROKEN');
-- Expect 0.

-- 9. POSITION_EPISODE_KEY is a 64-char SHA2 hex string.
SELECT 'BAD_EPISODE_KEY_LEN' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.DAILY_POSITION_VERDICT
 WHERE AS_OF_DATE = CURRENT_DATE()
   AND LENGTH(POSITION_EPISODE_KEY) <> 64;
-- Expect 0.

-- 10. Idempotency: rerun and assert same row count for today.
CALL MIP.APP.SP_RUN_DAILY_POSITION_VERDICT(CURRENT_DATE());
SELECT 'VERDICT_ROWS_TODAY_AFTER_RERUN' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.DAILY_POSITION_VERDICT
 WHERE AS_OF_DATE = CURRENT_DATE();

-- 11. Lifecycle SP runs cleanly.
CALL MIP.APP.SP_UPDATE_SHADOW_POSITION_LIFECYCLE(CURRENT_DATE());

-- 12. Lifecycle row count is at least the verdict row count for today
--     (every open position should have an OPEN lifecycle row).
SELECT
  'LIFECYCLE_ROW_GAP' AS CHECK_NAME,
  (SELECT COUNT(*) FROM MIP.APP.DAILY_POSITION_VERDICT WHERE AS_OF_DATE = CURRENT_DATE())
    - (SELECT COUNT(DISTINCT POSITION_EPISODE_KEY) FROM MIP.APP.SHADOW_POSITION_LIFECYCLE
        WHERE POSITION_EPISODE_KEY IN (
          SELECT POSITION_EPISODE_KEY FROM MIP.APP.DAILY_POSITION_VERDICT
           WHERE AS_OF_DATE = CURRENT_DATE()
        )) AS N;
-- Expect 0.

-- 13. Mart view: latest comparison returns rows joined by POSITION_EPISODE_KEY.
SELECT 'COMPARISON_ROWS_TODAY' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.MART.V_POSITION_HEALTH_COMPARISON_LATEST
 WHERE AS_OF_DATE = CURRENT_DATE();

-- 14. Sample first 10 comparison rows.
SELECT
  AS_OF_DATE,
  PORTFOLIO_ID,
  SYMBOL,
  REAL_VERDICT,
  REAL_HEALTH_STATE,
  REAL_SEVERITY,
  SHADOW_VERDICT,
  SHADOW_ACTION_BIAS,
  AGREEMENT_LABEL,
  SHADOW_STATUS,
  REALIZED_RETURN_SHADOW_PCT
FROM MIP.MART.V_POSITION_HEALTH_COMPARISON_LATEST
ORDER BY PORTFOLIO_ID, SYMBOL
LIMIT 10;

-- 15. Sample 5 verdict rows with summary fields.
SELECT
  AS_OF_DATE, SYMBOL, VERDICT, HEALTH_STATE, SEVERITY,
  BASELINE_QUALITY, THESIS_INTEGRITY, PATH_QUALITY, REGIME_ALIGNMENT,
  TIME_EFFICIENCY, FRAGILITY, HORIZON_SOURCE_CODE,
  PRIMARY_REASON_CODE, OBSERVATION_SUMMARY, VERDICT_SUMMARY, WHY_SUMMARY
FROM MIP.APP.DAILY_POSITION_VERDICT
WHERE AS_OF_DATE = CURRENT_DATE()
ORDER BY SYMBOL
LIMIT 5;

-- 16. Lifecycle status sample.
SELECT POSITION_EPISODE_KEY, SYMBOL, SHADOW_STATUS, LIFECYCLE_STATE,
       SHADOW_ENTRY_DATE, SHADOW_EXIT_DATE, REALIZED_RETURN_SHADOW_PCT, DAYS_SINCE_SHADOW_ENTRY
FROM MIP.MART.V_SHADOW_POSITION_LIFECYCLE_STATUS
ORDER BY SHADOW_STATUS, SYMBOL
LIMIT 10;

-- 17. Agent presence (Snowflake-side existence check).
SHOW AGENTS LIKE 'POSITION_HEALTH_REVIEW_AGENT' IN SCHEMA MIP.APP;
