use role MIP_ADMIN_ROLE;
use database MIP;

select 'COMMITTEE_RUN_TABLE_EXISTS' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.TABLES
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'COMMITTEE_RUN';

select 'COMMITTEE_ROLE_OUTPUT_TABLE_EXISTS' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.TABLES
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'COMMITTEE_ROLE_OUTPUT';

select 'COMMITTEE_VERDICT_TABLE_EXISTS' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.TABLES
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'COMMITTEE_VERDICT';

select 'LIVE_ACTIONS_COMMITTEE_REQUIRED_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'COMMITTEE_REQUIRED';

select 'LIVE_ACTIONS_COMMITTEE_STATUS_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'COMMITTEE_STATUS';

select 'LIVE_ACTIONS_COMMITTEE_RUN_ID_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'COMMITTEE_RUN_ID';

select 'LIVE_ACTIONS_COMMITTEE_COMPLETED_TS_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'COMMITTEE_COMPLETED_TS';

select 'LIVE_ACTIONS_COMMITTEE_VERDICT_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'COMMITTEE_VERDICT';

