use role MIP_ADMIN_ROLE;
use database MIP;

select 'LIVE_ACTIONS_TRAINING_QUALIFICATION_SNAPSHOT_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TRAINING_QUALIFICATION_SNAPSHOT';

select 'LIVE_ACTIONS_TRAINING_LIVE_ELIGIBLE_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TRAINING_LIVE_ELIGIBLE';

select 'LIVE_ACTIONS_TRAINING_RANK_IMPACT_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TRAINING_RANK_IMPACT';

select 'LIVE_ACTIONS_TRAINING_SIZE_CAP_FACTOR_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TRAINING_SIZE_CAP_FACTOR';

