use role MIP_ADMIN_ROLE;
use database MIP;

select 'LIVE_ACTIONS_TARGET_EXPECTATION_SNAPSHOT_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TARGET_EXPECTATION_SNAPSHOT';

select 'LIVE_ACTIONS_TARGET_OPEN_CONDITION_FACTOR_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TARGET_OPEN_CONDITION_FACTOR';

select 'LIVE_ACTIONS_TARGET_EXPECTATION_POLICY_VERSION_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'TARGET_EXPECTATION_POLICY_VERSION';

