use role MIP_ADMIN_ROLE;
use database MIP;

select 'LIVE_ACTIONS_NEWS_CONTEXT_SNAPSHOT_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'NEWS_CONTEXT_SNAPSHOT';

select 'LIVE_ACTIONS_NEWS_CONTEXT_STATE_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'NEWS_CONTEXT_STATE';

select 'LIVE_ACTIONS_NEWS_EVENT_SHOCK_FLAG_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'NEWS_EVENT_SHOCK_FLAG';

select 'LIVE_ACTIONS_NEWS_FRESHNESS_BUCKET_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'NEWS_FRESHNESS_BUCKET';

select 'LIVE_ACTIONS_NEWS_CONTEXT_POLICY_VERSION_COL' as check_name, count(*) as cnt
from MIP.INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'LIVE'
  and TABLE_NAME = 'LIVE_ACTIONS'
  and COLUMN_NAME = 'NEWS_CONTEXT_POLICY_VERSION';

