-- Smoke: Committee 2.0 objects exist and snapshot linkage is sane.
-- Run after deploying 540_committee2_tables.sql + 520 SP + grants migration.

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE WAREHOUSE MIP_WH_XS;

SELECT 'STRUCTURAL_PROPOSAL_SNAPSHOT' AS OBJ, COUNT(*) AS CNT FROM MIP.APP.STRUCTURAL_PROPOSAL_SNAPSHOT;
SELECT 'COMMITTEE_HEARING' AS OBJ, COUNT(*) AS CNT FROM MIP.APP.COMMITTEE_HEARING;
SELECT 'COMMITTEE_FINAL_DECISION' AS OBJ, COUNT(*) AS CNT FROM MIP.APP.COMMITTEE_FINAL_DECISION;

-- Proposals without snapshots (informational; new proposals should have snapshots after propose SP)
SELECT COUNT(*) AS PROPOSALS_MISSING_SNAPSHOT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
WHERE NOT EXISTS (
  SELECT 1 FROM MIP.APP.STRUCTURAL_PROPOSAL_SNAPSHOT s WHERE s.PROPOSAL_ID = p.PROPOSAL_ID
);

SELECT CONFIG_KEY, CONFIG_VALUE
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY = 'COMMITTEE2_ENABLED';
