-- Phase 2 smoke: politician trade disclosure table + flags (no DML required for pass).

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

SELECT CONFIG_KEY, CONFIG_VALUE
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY IN (
    'COMMITTEE2_CONTEXT_DISCLOSURE_ENABLED',
    'COMMITTEE2_LIVE_POLITICIAN_DISCLOSURE_ENABLED'
)
ORDER BY CONFIG_KEY;

SELECT COUNT(*) AS disclosure_row_count FROM MIP.APP.PUBLIC_DISCLOSURE_TRANSACTION;

-- TRADE_DATE column present (empty result set is OK).
SELECT TRADE_DATE FROM MIP.APP.PUBLIC_DISCLOSURE_TRANSACTION WHERE 1 = 0;
