/* ================================================================
   41_committee_bakeoff_smoke.sql
   Smoke tests for the Committee Bake-off Sidecar.
   Read-only checks + a single CALL to refresh the sidecar tables.
   No live/proposal/committee/IBKR objects are touched.
   ================================================================ */

USE ROLE MIP_ADMIN_ROLE;
USE WAREHOUSE MIP_WH_XS;
USE DATABASE MIP;
USE SCHEMA APP;

-- 1. Refresh the sidecar.
CALL MIP.APP.SP_REFRESH_COMMITTEE_BAKEOFF();

-- 2. Latch row counts by board and stance distribution.
SELECT BOARD_KIND, RAW_STANCE, NORMALIZED_ACTION, CONFIG_STATUS, COUNT(*) AS N
  FROM MIP.APP.COMMITTEE_BAKEOFF_LATCH
 GROUP BY BOARD_KIND, RAW_STANCE, NORMALIZED_ACTION, CONFIG_STATUS
 ORDER BY BOARD_KIND, NORMALIZED_ACTION, RAW_STANCE;

-- 3. Outcomes by board and raw outcome.
SELECT BOARD_KIND, RAW_OUTCOME, SCORING_EXCLUDED_FLAG, COUNT(*) AS N
  FROM MIP.APP.COMMITTEE_BAKEOFF_OUTCOME
 GROUP BY BOARD_KIND, RAW_OUTCOME, SCORING_EXCLUDED_FLAG
 ORDER BY BOARD_KIND, RAW_OUTCOME;

-- 4. Comparison label distribution.
SELECT * FROM MIP.MART.V_COMMITTEE_BAKEOFF_LABEL_DIST;

-- 5. Sanity check: every latch has a matching outcome.
SELECT 'LATCH_WITHOUT_OUTCOME' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.COMMITTEE_BAKEOFF_LATCH l
  LEFT JOIN MIP.APP.COMMITTEE_BAKEOFF_OUTCOME o
        ON o.LATCH_ID = l.LATCH_ID
 WHERE o.OUTCOME_ID IS NULL;

-- 6. Sanity check: outcomes never have CASH return != 0.
SELECT 'CASH_OUTCOME_NONZERO_RETURN' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.COMMITTEE_BAKEOFF_OUTCOME
 WHERE NORMALIZED_ACTION = 'CASH'
   AND COALESCE(REALIZED_RETURN_PCT, 0) <> 0;

-- 7. Sanity check: UNSCORABLE rows are always excluded.
SELECT 'UNSCORABLE_NOT_EXCLUDED' AS CHECK_NAME, COUNT(*) AS N
  FROM MIP.APP.COMMITTEE_BAKEOFF_OUTCOME
 WHERE LATCH_CONFIG_STATUS = 'UNSCORABLE'
   AND SCORING_EXCLUDED_FLAG = FALSE;

-- 8. Per-opportunity wide view first 20 rows.
SELECT PROPOSAL_ID, SYMBOL,
       REAL_RAW_STANCE, REAL_ACTION, REAL_OUTCOME, REAL_RETURN,
       SHADOW_RAW_STANCE, SHADOW_ACTION, SHADOW_OUTCOME, SHADOW_RETURN,
       COMPARISON_LABEL
  FROM MIP.MART.V_COMMITTEE_BAKEOFF_OPPORTUNITIES
 ORDER BY FIRST_DECISION_TS
 LIMIT 20;

-- 9. Scorecard top strip.
SELECT * FROM MIP.MART.V_COMMITTEE_BAKEOFF_SCORECARD;

-- 10. MTD recommendation.
SELECT MTD_RECOMMENDATION,
       SCORED_OPPORTUNITIES, REAL_AVG_RETURN, SHADOW_AVG_RETURN,
       AVG_RETURN_DELTA_REAL_MINUS_SHADOW
  FROM MIP.MART.V_COMMITTEE_BAKEOFF_MTD;
