-- Read-only/feature-local smoke for standalone Price Action Analyser SQL assets.
-- This script never mutates proposal, authority, decision, action, or order data.
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

SET proposals_before = (SELECT COUNT(*) FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS);
SET authority_before = (SELECT COUNT(*) FROM MIP.APP.AGENTIC_REVALIDATION_AUTHORITY);
SET decisions_before = (SELECT COUNT(*) FROM MIP.APP.COMMITTEE_FINAL_DECISION);
SET actions_before = (SELECT COUNT(*) FROM MIP.LIVE.LIVE_ACTIONS);
SET orders_before = (SELECT COUNT(*) FROM MIP.LIVE.LIVE_ORDERS);

-- Object and corrected-column contract.
SELECT
    COUNT_IF(TABLE_NAME = 'PRICE_ACTION_ANALYSER_AUDIT') > 0 AS AUDIT_EXISTS,
    COUNT_IF(
        TABLE_NAME = 'PRICE_ACTION_ANALYSER_AUDIT'
        AND COLUMN_NAME = 'METHODOLOGIST_OUTPUT_JSON'
    ) = 1 AS METHODOLOGIST_COLUMN_EXISTS
FROM MIP.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'KNOWLEDGE'
  AND TABLE_NAME = 'PRICE_ACTION_ANALYSER_AUDIT';

-- All required config keys exist with expected safe defaults/caps. This does not
-- require RAG/LLM to remain false after an operator deliberately enables them.
WITH expected(CONFIG_KEY, EXPECTED_NEW_DEFAULT) AS (
    SELECT column1, column2
    FROM VALUES
      ('PRICE_ACTION_ANALYSER_ENABLED', 'true'),
      ('PRICE_ACTION_ANALYSER_PIVOT_LEFT', '2'),
      ('PRICE_ACTION_ANALYSER_PIVOT_RIGHT', '2'),
      ('PRICE_ACTION_ANALYSER_MAX_LOOKBACK_BARS', '250'),
      ('PRICE_ACTION_ANALYSER_RAG_ENABLED', 'false'),
      ('PRICE_ACTION_ANALYSER_RAG_MAX_CALLS', '3'),
      ('PRICE_ACTION_ANALYSER_RAG_MAX_RETRIES', '0'),
      ('PRICE_ACTION_ANALYSER_RAG_MAX_TOTAL_CARDS', '8'),
      ('PRICE_ACTION_ANALYSER_RAG_MAX_CARDS_PER_TOPIC', '2'),
      ('PRICE_ACTION_ANALYSER_RAG_MAX_CARD_CHARS', '900'),
      ('PRICE_ACTION_ANALYSER_RAG_MAX_TOTAL_CHARS', '8000'),
      ('PRICE_ACTION_ANALYSER_RAG_TIMEOUT_SECONDS', '10'),
      ('PRICE_ACTION_ANALYSER_LLM_ENABLED', 'false'),
      ('PRICE_ACTION_ANALYSER_AUDIT_ENABLED', 'true')
)
SELECT
    COUNT(*) = 14 AS ALL_CONFIG_KEYS_EXIST,
    COUNT_IF(c.CONFIG_VALUE IS NULL) = 0 AS NO_CONFIG_VALUES_NULL,
    OBJECT_AGG(e.CONFIG_KEY, TO_VARIANT(c.CONFIG_VALUE)) AS OBSERVED_VALUES
FROM expected e
LEFT JOIN MIP.APP.APP_CONFIG c ON c.CONFIG_KEY = e.CONFIG_KEY;

-- Contract checks avoid Cortex cost: unsupported side/topic return before search.
CALL MIP.KNOWLEDGE.SP_SEARCH_PRICE_ACTION_KNOWLEDGE(
    'daily trend and range', 'MARKET_STRUCTURE', 99, 'SHORT'
);
CALL MIP.KNOWLEDGE.SP_SEARCH_PRICE_ACTION_KNOWLEDGE(
    'daily trend and range', 'NOT_A_GROUP', 2, 'LONG'
);

-- Invariance proof for all explicitly protected tables.
SELECT
    $proposals_before = (SELECT COUNT(*) FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS)
        AS PROPOSALS_UNCHANGED,
    $authority_before = (SELECT COUNT(*) FROM MIP.APP.AGENTIC_REVALIDATION_AUTHORITY)
        AS AUTHORITY_UNCHANGED,
    $decisions_before = (SELECT COUNT(*) FROM MIP.APP.COMMITTEE_FINAL_DECISION)
        AS FINAL_DECISIONS_UNCHANGED,
    $actions_before = (SELECT COUNT(*) FROM MIP.LIVE.LIVE_ACTIONS)
        AS LIVE_ACTIONS_UNCHANGED,
    $orders_before = (SELECT COUNT(*) FROM MIP.LIVE.LIVE_ORDERS)
        AS LIVE_ORDERS_UNCHANGED;
