-- Smoke: PAA proposal-panel pre-screen config keys.
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT
    'PAA_PRESCREEN_CONFIG' AS CHECK_NAME,
    COUNT(*) AS KEY_COUNT,
    IFF(COUNT(*) = 6, 'PASS', 'FAIL') AS STATUS
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY IN (
    'PROPOSAL_BOARD_PAA_PRESCREEN_ENABLED',
    'PROPOSAL_BOARD_PAA_TOP_N',
    'PROPOSAL_BOARD_PAA_MAX_SYMBOLS',
    'PROPOSAL_BOARD_PAA_MAX_LLM_CALLS',
    'PROPOSAL_BOARD_PAA_MAX_USD_ESTIMATE',
    'PROPOSAL_BOARD_PAA_LOOKBACK_BARS'
);

SELECT
    'PAA_TOP_N_DEFAULT' AS CHECK_NAME,
    CONFIG_VALUE AS TOP_N,
    IFF(CONFIG_VALUE = '30', 'PASS', 'FAIL') AS STATUS
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY = 'PROPOSAL_BOARD_PAA_TOP_N';

SELECT
    'PAA_ENABLED_SAFE_DEFAULT' AS CHECK_NAME,
    CONFIG_VALUE AS ENABLED,
    IFF(CONFIG_VALUE IN ('false', '0'), 'PASS', 'REVIEW') AS STATUS
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY = 'PROPOSAL_BOARD_PAA_PRESCREEN_ENABLED';
