-- Brooks Intraday Lab — table existence smoke
USE DATABASE MIP;
USE SCHEMA APP;

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'APP'
  AND TABLE_NAME IN (
    'BROOKS_INTRADAY_RUN',
    'BROOKS_INTRADAY_DOSSIER',
    'BROOKS_INTRADAY_BAR_OBSERVATION',
    'BROOKS_INTRADAY_PATTERN_INSTANCE',
    'BROOKS_INTRADAY_SIM_TRADE',
    'BROOKS_INTRADAY_BLOCKED_SIGNAL'
  )
ORDER BY TABLE_NAME;
