-- Brooks Intraday Lab Phase 2 — dossier column smoke
USE DATABASE MIP;
USE SCHEMA APP;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'APP'
  AND TABLE_NAME = 'BROOKS_INTRADAY_DOSSIER'
  AND COLUMN_NAME IN (
    'BOARD_RUN_ID',
    'NORMALIZED_STATUS',
    'COMPILER_VERSION',
    'SOURCE_HASH'
  )
ORDER BY COLUMN_NAME;
