-- Smoke: Brooks historical bar table
USE DATABASE MIP;
USE SCHEMA APP;

SELECT COUNT(*) AS TABLE_EXISTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'APP'
  AND TABLE_NAME = 'BROOKS_INTRADAY_HISTORICAL_BAR';
