-- Brooks Intraday Lab Phase 3 replay smoke (pilot run)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT COUNT(*) AS REPLAY_STATE_ROWS
FROM MIP.APP.BROOKS_INTRADAY_REPLAY_STATE
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';

SELECT STATUS, CONFIG_JSON:replay_cursor:completed_steps::INT AS COMPLETED_STEPS
FROM MIP.APP.BROOKS_INTRADAY_RUN
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';

SELECT
    COUNT(*) AS OBSERVATIONS,
    COUNT(DISTINCT BAR_TS) AS SHARED_SLICES
FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';
