-- Phase 4 objective observations smoke (pilot run — adjust REPLAY_ATTEMPT_ID after full replay)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT COUNT(*) AS LEGACY_P3_OBS
FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND REPLAY_ATTEMPT_ID LIKE 'p3:%';

SELECT RULESET_VERSION, COUNT(*) AS OBS
FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND RULESET_VERSION = 'BROOKS_OBJECTIVE_RULESET_V0_1'
GROUP BY RULESET_VERSION;

SELECT CONFIG_JSON:bars_frozen::BOOLEAN AS BARS_FROZEN,
       CONFIG_JSON:dossiers_frozen::BOOLEAN AS DOSSIERS_FROZEN
FROM MIP.APP.BROOKS_INTRADAY_RUN
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';
