-- Phase 4 designated review baseline completeness
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT REPLAY_ATTEMPT_ID, STATUS, OBSERVATION_COUNT, OBSERVATION_SEQUENCE_HASH, REVIEW_STATUS
FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND REVIEW_STATUS = 'DESIGNATED_REVIEW_BASELINE';

SELECT COUNT(*) AS OBS, COUNT(DISTINCT BAR_TS) AS SLICES
FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION o
WHERE o.RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND o.REPLAY_ATTEMPT_ID IN (
      SELECT REPLAY_ATTEMPT_ID FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
      WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
        AND REVIEW_STATUS = 'DESIGNATED_REVIEW_BASELINE'
  );

SELECT SYMBOL, COUNT(*) AS C
FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION o
WHERE o.RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND o.REPLAY_ATTEMPT_ID IN (
      SELECT REPLAY_ATTEMPT_ID FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
      WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
        AND REVIEW_STATUS = 'DESIGNATED_REVIEW_BASELINE'
  )
GROUP BY SYMBOL
ORDER BY SYMBOL;

SELECT TRADING_DATE, COUNT(DISTINCT BAR_TS) AS SLICES
FROM MIP.APP.BROOKS_INTRADAY_BAR_OBSERVATION o
WHERE o.RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND o.REPLAY_ATTEMPT_ID IN (
      SELECT REPLAY_ATTEMPT_ID FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
      WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
        AND REVIEW_STATUS = 'DESIGNATED_REVIEW_BASELINE'
  )
GROUP BY TRADING_DATE
ORDER BY TRADING_DATE;
