-- Phase 5 pattern replay smoke
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT REPLAY_ATTEMPT_ID, RULESET_VERSION, STATUS, OBSERVATION_COUNT, OBSERVATION_SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  AND RULESET_VERSION = 'BROOKS_PATTERN_RULESET_V0_1'
ORDER BY CREATED_AT_UTC DESC
LIMIT 1;

SELECT COUNT(*) AS PATTERN_INSTANCES
FROM MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';

SELECT COUNT(*) AS BAR_LINKS, COUNT(DISTINCT BAR_TS) AS SLICES
FROM MIP.APP.BROOKS_INTRADAY_BAR_PATTERN_LINK
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';

SELECT OBSERVATION_COUNT, OBSERVATION_SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
WHERE REPLAY_ATTEMPT_ID = '53a502f5-dec4-4bff-8106-f6637574163e';
