-- Phase 5B: V0.1 preserved, V0.2 pattern replay
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT REPLAY_ATTEMPT_ID, RULESET_VERSION, STATUS, OBSERVATION_COUNT, OBSERVATION_SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
WHERE REPLAY_ATTEMPT_ID = '91d9919a-02e2-4a70-a4c4-2c7a63118636';

SELECT REPLAY_ATTEMPT_ID, RULESET_VERSION, STATUS, OBSERVATION_COUNT, OBSERVATION_SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
WHERE RULESET_VERSION = 'BROOKS_PATTERN_RULESET_V0_2'
  AND RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
ORDER BY CREATED_AT_UTC DESC
LIMIT 1;

SELECT COUNT(*) AS V01_INSTANCES
FROM MIP.APP.BROOKS_INTRADAY_PATTERN_INSTANCE
WHERE REPLAY_ATTEMPT_ID = '91d9919a-02e2-4a70-a4c4-2c7a63118636';

SELECT COUNT(*) AS V02_LINKS, COUNT(DISTINCT BAR_TS) AS SLICES
FROM MIP.APP.BROOKS_INTRADAY_BAR_PATTERN_LINK
WHERE REPLAY_ATTEMPT_ID IN (
  SELECT REPLAY_ATTEMPT_ID FROM MIP.APP.BROOKS_INTRADAY_REPLAY_ATTEMPT
  WHERE RULESET_VERSION = 'BROOKS_PATTERN_RULESET_V0_2'
    AND RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
  ORDER BY CREATED_AT_UTC DESC LIMIT 1
);
