-- Phase 6B — V0.2 context attempt smoke (run after brooks_phase6b_complete_v02_replay.py)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT CONTEXT_ATTEMPT_ID, CONTEXT_RULESET_VERSION, STATUS, ROW_COUNT, SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT
WHERE CONTEXT_RULESET_VERSION = 'BROOKS_CONTEXT_RULESET_V0_2'
  AND RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
ORDER BY CREATED_AT_UTC DESC
LIMIT 3;

-- Latest V0.2 action distribution
WITH latest AS (
    SELECT CONTEXT_ATTEMPT_ID
    FROM MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT
    WHERE CONTEXT_RULESET_VERSION = 'BROOKS_CONTEXT_RULESET_V0_2'
      AND RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
      AND STATUS = 'COMPLETED'
    ORDER BY CREATED_AT_UTC DESC
    LIMIT 1
)
SELECT o.SELECTED_ACTION, COUNT(*) AS CNT
FROM MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION o
JOIN latest l ON l.CONTEXT_ATTEMPT_ID = o.CONTEXT_ATTEMPT_ID
GROUP BY o.SELECTED_ACTION
ORDER BY CNT DESC;

-- V0.1 baseline attempt must remain intact
SELECT CONTEXT_ATTEMPT_ID, SEQUENCE_HASH, ROW_COUNT
FROM MIP.APP.BROOKS_INTRADAY_CONTEXT_ATTEMPT
WHERE CONTEXT_ATTEMPT_ID = '40d797ff-f707-4094-b195-16b0ec5e2434';
