-- Phase 7 — simulation gating smoke (V0.2 context only)
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT SIMULATION_ATTEMPT_ID, CONTEXT_ATTEMPT_ID, CONTEXT_RULESET_VERSION,
       SIMULATION_RULESET_VERSION, STATUS, TRADE_COUNT, BLOCKED_SIGNAL_COUNT,
       STARTING_CASH, ENDING_CASH, REALIZED_PNL, SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
ORDER BY CREATED_AT_UTC DESC
LIMIT 3;

SELECT COUNT(*) AS SIM_TRADES
FROM MIP.APP.BROOKS_INTRADAY_SIM_TRADE
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';

SELECT BLOCK_REASON, COUNT(*) AS CNT
FROM MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74'
GROUP BY BLOCK_REASON
ORDER BY CNT DESC;
