-- Phase 7B — historical pilot simulation/context must remain unchanged
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT SIMULATION_ATTEMPT_ID, TRADE_COUNT, ENDING_CASH, REALIZED_PNL, SEQUENCE_HASH
FROM MIP.APP.BROOKS_INTRADAY_SIMULATION_ATTEMPT
WHERE SIMULATION_ATTEMPT_ID = '4bd264d3-c061-4bee-8534-c4eb99532438';

SELECT COUNT(*) AS CONSIDER_ENTRY_ROWS
FROM MIP.APP.BROOKS_INTRADAY_CONTEXT_OBSERVATION
WHERE CONTEXT_ATTEMPT_ID = '63ecc779-3dbb-4468-8bc1-a8bbd0f17342'
  AND SELECTED_ACTION = 'CONSIDER_ENTRY';

SELECT COUNT(*) AS HISTORICAL_SIM_TRADES
FROM MIP.APP.BROOKS_INTRADAY_SIM_TRADE
WHERE RUN_ID = '4eababc8-88fe-4ebc-b47c-b65f6ec10c74';
