/* Smoke: Phase C SIMULATION_ATTEMPT_ID column + blocked PK shape */
USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM MIP.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'APP'
  AND TABLE_NAME IN ('BROOKS_INTRADAY_SIM_TRADE', 'BROOKS_INTRADAY_BLOCKED_SIGNAL')
  AND COLUMN_NAME = 'SIMULATION_ATTEMPT_ID'
ORDER BY TABLE_NAME;

SELECT COUNT(*) AS legacy_unscoped_blocked
FROM MIP.APP.BROOKS_INTRADAY_BLOCKED_SIGNAL
WHERE SIMULATION_ATTEMPT_ID = 'LEGACY_UNSCOPED';
