use role MIP_ADMIN_ROLE;
use database MIP;

-- Non-destructive portfolio consistency check.
-- Use this before/after any replay or repair.
select
    PORTFOLIO_ID,
    DAILY_TS,
    HEADER_LAST_RUN_ID,
    DAILY_RUN_ID,
    DAILY_CASH,
    DAILY_EQUITY_VALUE,
    DAILY_TOTAL_EQUITY,
    DAILY_OPEN_POSITIONS,
    CANONICAL_OPEN_POSITIONS,
    CANONICAL_OPEN_MV,
    LEDGER_IMPLIED_CASH,
    LEDGER_PLUS_CANONICAL_TOTAL,
    DIFF_DAILY_CASH_VS_LEDGER,
    DIFF_DAILY_TOTAL_VS_LEDGER_CANONICAL,
    DIFF_HEADER_VS_DAILY_TOTAL,
    FLAG_OPEN_POSITION_MISMATCH,
    FLAG_CASH_MISMATCH,
    FLAG_TOTAL_EQUITY_MISMATCH
from MIP.MART.V_PORTFOLIO_REALITY_CHECK
order by PORTFOLIO_ID;

-- Focused drift-only rows.
select *
from MIP.MART.V_PORTFOLIO_REALITY_CHECK
where FLAG_OPEN_POSITION_MISMATCH
   or FLAG_CASH_MISMATCH
   or FLAG_TOTAL_EQUITY_MISMATCH
order by PORTFOLIO_ID;
