USE ROLE MIP_UI_API_ROLE;
USE WAREHOUSE MIP_WH_XS;
SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
    'MIP.KNOWLEDGE.LITERATURE_INTRADAY_ADVISER_SEARCH_SERVICE',
    '{"query": "bull trend bar", "columns": ["CARD_ID", "CONCEPT_NAME"], "limit": 2}'
) AS RAW;
