/*  ================================================================
    phase4_geometry_validation_smoke.sql
    Direction / Geometry Fix — Smoke Checks

    Verifies:
      1. No EXECUTABLE LONG proposal has invalidation above/inside entry zone.
      2. No EXECUTABLE SHORT proposal has invalidation below/inside entry zone.
      3. No EXECUTABLE proposal has SETUP_EVENT_ID NULL (direction mismatch).
      4. Existing 178 rows survived the migration (all have EXECUTION_POLICY_STATUS).
      5. Proposal 3002 no longer links SETUP_EVENT_ID to SHORT setup 47538.
      6. Cross-direction evidence is visible but marked non-executable.
      7. Execution policy status distribution report.
    ================================================================ */

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;
USE SCHEMA APP;
USE WAREHOUSE MIP_WH_XS;

-- ── 1. No EXECUTABLE LONG with bad invalidation geometry ─────────────────
SELECT 'SMOKE_1_EXECUTABLE_LONG_BAD_GEOMETRY' AS CHECK_NAME,
       COUNT(*) AS VIOLATIONS,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE COALESCE(EXECUTION_POLICY_STATUS, 'EXECUTABLE') = 'EXECUTABLE'
  AND DIRECTION = 'LONG'
  AND PRICE_INVALIDATION_LEVEL IS NOT NULL
  AND ENTRY_ZONE_LOW IS NOT NULL
  AND PRICE_INVALIDATION_LEVEL >= ENTRY_ZONE_LOW;

-- ── 2. No EXECUTABLE SHORT with bad invalidation geometry ────────────────
SELECT 'SMOKE_2_EXECUTABLE_SHORT_BAD_GEOMETRY' AS CHECK_NAME,
       COUNT(*) AS VIOLATIONS,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE COALESCE(EXECUTION_POLICY_STATUS, 'EXECUTABLE') = 'EXECUTABLE'
  AND DIRECTION = 'SHORT'
  AND PRICE_INVALIDATION_LEVEL IS NOT NULL
  AND ENTRY_ZONE_HIGH IS NOT NULL
  AND PRICE_INVALIDATION_LEVEL <= ENTRY_ZONE_HIGH;

-- ── 3. No EXECUTABLE proposal with SETUP_EVENT_ID NULL ──────────────────
SELECT 'SMOKE_3_EXECUTABLE_WITH_NULL_SETUP_EVENT_ID' AS CHECK_NAME,
       COUNT(*) AS VIOLATIONS,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE COALESCE(EXECUTION_POLICY_STATUS, 'EXECUTABLE') = 'EXECUTABLE'
  AND SETUP_EVENT_ID IS NULL
  AND BOARD_RUN_ID IS NOT NULL;

-- ── 4. All existing 178 rows have EXECUTION_POLICY_STATUS set ────────────
SELECT 'SMOKE_4_EXISTING_ROWS_HAVE_POLICY_STATUS' AS CHECK_NAME,
       COUNT(*) AS ROWS_WITH_NULL_STATUS,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE EXECUTION_POLICY_STATUS IS NULL;

-- ── 5. Proposal 3002 — SETUP_EVENT_ID no longer links to SHORT setup 47538 ──
SELECT 'SMOKE_5_PROPOSAL_3002_SETUP_EVENT_ID_MISMATCH' AS CHECK_NAME,
       PROPOSAL_ID,
       SETUP_EVENT_ID,
       PRIMARY_EVIDENCE_SETUP_EVENT_ID,
       DIRECTION,
       EXECUTION_POLICY_STATUS,
       EXECUTION_POLICY_REASON
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE PROPOSAL_ID = 3002;

-- ── 6. Cross-direction evidence proposals are non-executable ─────────────
SELECT 'SMOKE_6_CROSS_DIRECTION_EVIDENCE_IS_NON_EXECUTABLE' AS CHECK_NAME,
       p.PROPOSAL_ID,
       p.DIRECTION AS PROPOSAL_DIRECTION,
       p.SETUP_EVENT_ID,
       p.PRIMARY_EVIDENCE_SETUP_EVENT_ID,
       se.DIRECTION AS EVIDENCE_DIRECTION,
       p.EXECUTION_POLICY_STATUS,
       p.EXECUTION_POLICY_REASON,
       p.IS_RESEARCH_ONLY
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
LEFT JOIN MIP.APP.STRUCTURAL_SETUP_EVENTS se
  ON se.SETUP_EVENT_ID = p.PRIMARY_EVIDENCE_SETUP_EVENT_ID
WHERE p.BOARD_RUN_ID IS NOT NULL
  AND se.DIRECTION IS NOT NULL
  AND se.DIRECTION != p.DIRECTION
ORDER BY p.PROPOSAL_ID;

-- ── 7. Execution policy status distribution ──────────────────────────────
SELECT 'SMOKE_7_EXECUTION_POLICY_DISTRIBUTION' AS CHECK_NAME,
       EXECUTION_POLICY_STATUS,
       EXECUTION_POLICY_REASON,
       DIRECTION,
       IS_RESEARCH_ONLY,
       COUNT(*) AS ROW_COUNT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
GROUP BY EXECUTION_POLICY_STATUS, EXECUTION_POLICY_REASON, DIRECTION, IS_RESEARCH_ONLY
ORDER BY ROW_COUNT DESC;

-- ── 8. Phase 4 audit: PROPOSE_LONG proposals backed by SHORT evidence ────
SELECT 'SMOKE_8_LONG_PROPOSALS_WITH_SHORT_EVIDENCE' AS CHECK_NAME,
       p.PROPOSAL_ID,
       p.SYMBOL,
       p.DIRECTION AS PROPOSAL_DIRECTION,
       p.SETUP_FAMILY AS PROPOSAL_SETUP_FAMILY,
       p.PRIMARY_EVIDENCE_SETUP_EVENT_ID,
       se.DIRECTION AS EVIDENCE_DIRECTION,
       se.SETUP_FAMILY AS EVIDENCE_SETUP_FAMILY,
       p.BOARD_FINAL_VERDICT,
       p.STATUS,
       p.EXECUTION_POLICY_STATUS,
       p.EXECUTION_POLICY_REASON,
       p.CREATED_AT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
JOIN MIP.APP.STRUCTURAL_SETUP_EVENTS se
  ON se.SETUP_EVENT_ID = p.PRIMARY_EVIDENCE_SETUP_EVENT_ID
WHERE p.DIRECTION = 'LONG'
  AND se.DIRECTION = 'SHORT'
  AND p.BOARD_RUN_ID IS NOT NULL
ORDER BY p.PROPOSAL_ID;

-- ── 9. LPA gate verification — confirm EXECUTION_POLICY_STATUS column exists ──
SELECT 'SMOKE_9_EXECUTION_POLICY_COLUMN_EXISTS' AS CHECK_NAME,
       COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM MIP.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'STRUCTURAL_TRADE_PROPOSALS'
  AND COLUMN_NAME IN ('EXECUTION_POLICY_STATUS','EXECUTION_POLICY_REASON','IS_RESEARCH_ONLY')
ORDER BY COLUMN_NAME;

-- ── 10. Chair PROPOSE_SHORT verdicts fire when short evidence is present ────
-- After the Chair prompt cleanup (removing the WATCH_SHORT-on-short-disabled
-- override), at least one PROPOSE_SHORT must appear in the most recent
-- completed board run that included any SHORT structural evidence. A run with
-- short structural evidence that emits only WATCH_SHORT and no PROPOSE_SHORT
-- indicates the Chair is still suppressing shorts at the prompt layer.
WITH latest_complete_run AS (
    SELECT RUN_ID, AS_OF_DATE
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
    ORDER BY STARTED_AT DESC
    LIMIT 1
),
run_short_evidence AS (
    SELECT COUNT(*) AS short_evidence_count
    FROM MIP.APP.PROPOSAL_BOARD_SYMBOL_DOSSIER_SNAPSHOT s
    JOIN latest_complete_run r ON r.RUN_ID = s.RUN_ID
    JOIN MIP.APP.STRUCTURAL_SETUP_EVENTS ev
      ON ev.SETUP_EVENT_ID = s.PRIMARY_EVIDENCE_SETUP_EVENT_ID
    WHERE ev.DIRECTION = 'SHORT'
),
run_short_proposals AS (
    SELECT COUNT(*) AS propose_short_count
    FROM MIP.APP.PROPOSAL_BOARD_FINAL_SLATE_V2 f
    JOIN latest_complete_run r ON r.RUN_ID = f.RUN_ID
    WHERE f.FINAL_ACTION = 'PROPOSE_SHORT'
)
SELECT 'SMOKE_10_PROPOSE_SHORT_FIRES_WHEN_EVIDENCE_EXISTS' AS CHECK_NAME,
       (SELECT RUN_ID FROM latest_complete_run)             AS LATEST_COMPLETE_RUN,
       (SELECT short_evidence_count FROM run_short_evidence) AS SHORT_EVIDENCE_DOSSIERS,
       (SELECT propose_short_count FROM run_short_proposals) AS PROPOSE_SHORT_VERDICTS,
       CASE
           WHEN (SELECT short_evidence_count FROM run_short_evidence) = 0 THEN 'SKIP_NO_SHORT_EVIDENCE'
           WHEN (SELECT propose_short_count FROM run_short_proposals) > 0 THEN 'PASS'
           ELSE 'FAIL'
       END AS RESULT;

-- ── 11. APP_CONFIG: PROPOSAL_BOARD_SHORT_LIVE_ENABLED current value ─────────
-- Informational. When unset or false, all PROPOSE_SHORT verdicts must be
-- materialised with EXECUTION_POLICY_STATUS = POLICY_BLOCKED /
-- EXECUTION_POLICY_REASON = SHORT_LIVE_DISABLED. Flip to true (via UPDATE)
-- only after IBKR paper-account verification is complete.
SELECT 'SMOKE_11_SHORT_LIVE_CONFIG' AS CHECK_NAME,
       COALESCE(MAX(CASE WHEN CONFIG_KEY = 'PROPOSAL_BOARD_SHORT_LIVE_ENABLED'
                         THEN CONFIG_VALUE END), '(unset → default FALSE)') AS SHORT_LIVE_ENABLED_VALUE,
       MAX(CASE WHEN CONFIG_KEY = 'PROPOSAL_BOARD_SHORT_LIVE_ENABLED'
                THEN UPDATED_AT END) AS UPDATED_AT
FROM MIP.APP.APP_CONFIG
WHERE CONFIG_KEY = 'PROPOSAL_BOARD_SHORT_LIVE_ENABLED'
   OR 1=1;  -- ensure single-row report even when unset
