/* ================================================================
   phase4_symbol_dossier_board_cutover_smoke.sql
   Post-cutover validation for the active Phase 4 symbol-dossier board.
   ================================================================ */

USE ROLE MIP_ADMIN_ROLE;
USE DATABASE MIP;

WITH latest AS (
    SELECT *
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'latest_phase4_run' AS CHECK_NAME,
    RUN_ID,
    AS_OF_DATE,
    CANDIDATE_COUNT AS SYMBOL_DOSSIER_COUNT,
    FINAL_PROPOSAL_COUNT AS PUBLISHED_COUNT,
    MODEL_CONFIG_JSON
FROM latest;

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'agent_outcomes' AS CHECK_NAME,
    COUNT(*) AS AGENT_OUTCOME_COUNT,
    COUNT(DISTINCT DOSSIER_ID) AS DOSSIERS_WITH_OUTCOMES
FROM MIP.APP.PROPOSAL_BOARD_AGENT_OUTCOME_V2
WHERE RUN_ID = (SELECT RUN_ID FROM latest);

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'thesis_distribution' AS CHECK_NAME,
    FINAL_ACTION,
    COUNT(*) AS N
FROM MIP.APP.PROPOSAL_BOARD_THESIS_VERDICT
WHERE RUN_ID = (SELECT RUN_ID FROM latest)
GROUP BY FINAL_ACTION
ORDER BY FINAL_ACTION;

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'published_proposals' AS CHECK_NAME,
    p.PROPOSAL_ID,
    p.SYMBOL,
    p.DIRECTION,
    p.SETUP_FAMILY,
    p.STATUS,
    p.PRIMARY_EVIDENCE_SETUP_EVENT_ID,
    p.BOARD_PAYLOAD_JSON:direction_source::STRING AS DIRECTION_SOURCE,
    p.BOARD_PAYLOAD_JSON:primary_evidence_setup_event_id_role::STRING AS SETUP_EVENT_ROLE
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
WHERE p.BOARD_RUN_ID = (SELECT RUN_ID FROM latest)
ORDER BY p.PROPOSAL_ID;

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'short_thesis_policy' AS CHECK_NAME,
    COUNT_IF(v.FINAL_DIRECTION = 'SHORT') AS SHORT_THESIS_COUNT,
    COUNT_IF(v.FINAL_DIRECTION = 'SHORT' AND v.FINAL_ACTION = 'PROPOSE_SHORT') AS PROPOSE_SHORT_COUNT,
    COUNT_IF(v.FINAL_DIRECTION = 'SHORT' AND fs.PUBLICATION_STATUS = 'SHORT_RESEARCH_ONLY') AS SHORT_RESEARCH_ONLY_COUNT,
    MAX(s.SHORT_LIVE_ENABLED) AS SHORT_LIVE_ENABLED
FROM MIP.APP.PROPOSAL_BOARD_THESIS_VERDICT v
JOIN MIP.APP.PROPOSAL_BOARD_SYMBOL_DOSSIER_SNAPSHOT s
  ON s.RUN_ID = v.RUN_ID
 AND s.DOSSIER_ID = v.DOSSIER_ID
LEFT JOIN MIP.APP.PROPOSAL_BOARD_FINAL_SLATE_V2 fs
  ON fs.RUN_ID = v.RUN_ID
 AND fs.DOSSIER_ID = v.DOSSIER_ID
WHERE v.RUN_ID = (SELECT RUN_ID FROM latest);

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'focus_symbols' AS CHECK_NAME,
    SYMBOL,
    FINAL_ACTION,
    FINAL_DIRECTION,
    PRIMARY_REASON_CODE,
    FINAL_THESIS
FROM MIP.APP.PROPOSAL_BOARD_THESIS_VERDICT
WHERE RUN_ID = (SELECT RUN_ID FROM latest)
  AND SYMBOL IN ('CRWD', 'AAPL', 'PANW', 'AMZN')
ORDER BY SYMBOL;

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'output_errors' AS CHECK_NAME,
    COUNT(*) AS OUTPUT_ERROR_COUNT
FROM MIP.APP.PROPOSAL_BOARD_OUTPUT_ERROR
WHERE RUN_ID = (SELECT RUN_ID FROM latest);

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'active_proposal_health' AS CHECK_NAME,
    COUNT(*) AS ACTIVE_PROPOSALS,
    COUNT_IF(BOARD_RUN_ID <> (SELECT RUN_ID FROM latest)) AS ACTIVE_NOT_FROM_LATEST_RUN,
    COUNT(*) - COUNT(DISTINCT SYMBOL) AS DUPLICATE_ACTIVE_SYMBOL_COUNT,
    COUNT_IF(SETUP_FAMILY NOT ILIKE 'AGENTIC_%') AS NON_AGENTIC_SETUP_FAMILY_COUNT,
    COUNT_IF(BOARD_PAYLOAD_JSON:direction_source::STRING <> 'CHAIR_PORTFOLIO_PM.final_direction') AS BAD_DIRECTION_SOURCE_COUNT,
    COUNT_IF(BOARD_PAYLOAD_JSON:primary_evidence_setup_event_id_role::STRING <> 'EVIDENCE_ONLY_NOT_DIRECTION_SOURCE') AS BAD_SETUP_EVENT_ROLE_COUNT
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS
WHERE STATUS = 'PROPOSED';

WITH latest AS (
    SELECT RUN_ID
    FROM MIP.APP.PROPOSAL_BOARD_RUN
    WHERE RUN_STATUS = 'COMPLETE'
      AND MODEL_CONFIG_JSON:mode::STRING = 'symbol_dossier_agentic_thesis_board'
    ORDER BY STARTED_AT DESC
    LIMIT 1
)
SELECT
    'live_action_collision' AS CHECK_NAME,
    COUNT(*) AS IN_FLIGHT_COLLISIONS
FROM MIP.APP.STRUCTURAL_TRADE_PROPOSALS p
JOIN MIP.LIVE.LIVE_ACTIONS la
  ON la.SYMBOL = p.SYMBOL
 AND la.LIVE_INTENT_KIND = 'STRUCTURAL'
 AND la.STATUS IN ('PROPOSED','INTENT_APPROVED','PENDING_OPEN_VALIDATION','OPEN_BLOCKED','REVALIDATED_PASS','EXECUTION_REQUESTED')
WHERE p.STATUS = 'PROPOSED'
  AND p.BOARD_RUN_ID = (SELECT RUN_ID FROM latest)
  AND la.PROPOSAL_ID <> p.PROPOSAL_ID;

SELECT
    'committee_compatibility' AS CHECK_NAME,
    COUNT(*) AS COMMITTEE_VISIBLE_PROPOSALS
FROM MIP.MART.V_STRUCTURAL_PROPOSALS_FOR_COMMITTEE;
